// ==============================================================
// File       : buffered_axi_lite_uart_regression_test.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : buffered_axi_lite_uart regression test — runs smoke sequence then all COV sequence stubs.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   run_sequences      : Smoke + all COV stubs
//
// Dependencies:
//   buffered_axi_lite_uart_base_test
//   all COV seq stubs
//
// Portability    : Simulator-independent
// Impl. status   : generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Regression test: runs smoke sequence followed by all COV sequences.
// Additional COV sequences are added here as they are created.
// Start with: +UVM_TESTNAME=buffered_axi_lite_uart_regression_test
class buffered_axi_lite_uart_regression_test extends buffered_axi_lite_uart_base_test;
    `uvm_component_utils(buffered_axi_lite_uart_regression_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
    endfunction

    virtual task run_sequences(uvm_phase phase);
        buffered_axi_lite_uart_smoke_seq  smoke;
        seq_RCOV001_baud_tuning           cov001;
        seq_RCOV002_ctrl_parity           cov002;
        seq_RCOV003_ctrl_stop_bits           cov003;
        seq_RCOV004_fifo_status_rx_level           cov004;
        seq_RCOV005_fifo_status_tx_level           cov005;
        seq_RCOV006_timeout_val           cov006;
        seq_RCOV007_int_status_each_bit_independently           cov007;
        seq_RCOV008_int_status_overrun_int_status_rx_full           cov008;
        seq_RCOV009_int_status_timeout_int_status_rx_thresh           cov009;
        seq_RCOV010_axi_bresp           cov010;
        seq_RCOV011_axi_rresp           cov011;
        seq_RCOV012_axi_write_order           cov012;
        seq_RCOV013_baud_tuning_write_while_enabled           cov013;
        seq_RCOV014_scratch           cov014;
        seq_RCOV015_reset_values           cov015;
        seq_RCOV016_uart_en_control           cov016;
        seq_RCOV017_frame_structural           cov017;
        seq_RCOV018_readonly_ignore           cov018;
        seq_RCOV019_int_thresh_frame           cov019;

        smoke  = buffered_axi_lite_uart_smoke_seq::type_id::create("smoke");
        cov001 = seq_RCOV001_baud_tuning::type_id::create("cov001");
        cov002 = seq_RCOV002_ctrl_parity::type_id::create("cov002");
        cov003 = seq_RCOV003_ctrl_stop_bits::type_id::create("cov003");
        cov004 = seq_RCOV004_fifo_status_rx_level::type_id::create("cov004");
        cov005 = seq_RCOV005_fifo_status_tx_level::type_id::create("cov005");
        cov006 = seq_RCOV006_timeout_val::type_id::create("cov006");
        cov007 = seq_RCOV007_int_status_each_bit_independently::type_id::create("cov007");
        cov008 = seq_RCOV008_int_status_overrun_int_status_rx_full::type_id::create("cov008");
        cov009 = seq_RCOV009_int_status_timeout_int_status_rx_thresh::type_id::create("cov009");
        cov010 = seq_RCOV010_axi_bresp::type_id::create("cov010");
        cov011 = seq_RCOV011_axi_rresp::type_id::create("cov011");
        cov012 = seq_RCOV012_axi_write_order::type_id::create("cov012");
        cov013 = seq_RCOV013_baud_tuning_write_while_enabled::type_id::create("cov013");
        cov014 = seq_RCOV014_scratch::type_id::create("cov014");
        cov015 = seq_RCOV015_reset_values::type_id::create("cov015");
        cov016 = seq_RCOV016_uart_en_control::type_id::create("cov016");
        cov017 = seq_RCOV017_frame_structural::type_id::create("cov017");
        cov018 = seq_RCOV018_readonly_ignore::type_id::create("cov018");
        cov019 = seq_RCOV019_int_thresh_frame::type_id::create("cov019");

        smoke.start(env_h.agent.seqr);
        cov001.start(env_h.agent.seqr);
        cov002.start(env_h.agent.seqr);
        cov003.start(env_h.agent.seqr);
        cov004.start(env_h.agent.seqr);
        cov005.start(env_h.agent.seqr);
        cov006.start(env_h.agent.seqr);
        cov007.start(env_h.agent.seqr);
        cov008.start(env_h.agent.seqr);
        cov009.start(env_h.agent.seqr);
        cov010.start(env_h.agent.seqr);
        cov011.start(env_h.agent.seqr);
        cov012.start(env_h.agent.seqr);
        cov013.start(env_h.agent.seqr);
        cov014.start(env_h.agent.seqr);
        cov015.start(env_h.agent.seqr);
        cov016.start(env_h.agent.seqr);
        cov017.start(env_h.agent.seqr);
        cov018.start(env_h.agent.seqr);
        cov019.start(env_h.agent.seqr);
    endtask

endclass