// ==============================================================
// File       : buffered_axi_lite_uart_if.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : AXI-Lite interface bundle for buffered_axi_lite_uart DUT connections.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   Interface signals  : All DUT ports as logic signals
//
// Dependencies:
//   UVM 1.2
//
// Portability    : Simulator-independent
// Impl. status   : generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
interface buffered_axi_lite_uart_if (
    input logic clk
);
    // Signals mirroring buffered_axi_lite_uart non-clock ports

    logic axi_aclk;

    logic axi_aresetn;

    logic s_axi_awvalid;

    logic s_axi_awready;

    logic [7:0] s_axi_awaddr;

    logic [2:0] s_axi_awprot;

    logic s_axi_wvalid;

    logic s_axi_wready;

    logic [31:0] s_axi_wdata;

    logic [3:0] s_axi_wstrb;

    logic s_axi_bvalid;

    logic s_axi_bready;

    logic [1:0] s_axi_bresp;

    logic s_axi_arvalid;

    logic s_axi_arready;

    logic [7:0] s_axi_araddr;

    logic [2:0] s_axi_arprot;

    logic s_axi_rvalid;

    logic s_axi_rready;

    logic [31:0] s_axi_rdata;

    logic [1:0] s_axi_rresp;

    logic uart_tx;

    logic uart_rx;

    logic irq;

endinterface