// ==============================================================
// File       : buffered_axi_lite_uart_smoke_seq.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : buffered_axi_lite_uart smoke sequence — single AXI-Lite write/read to first RW register.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body               : One write, one read, readback assertion
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
class buffered_axi_lite_uart_smoke_seq extends
    buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(buffered_axi_lite_uart_smoke_seq)

    function new(string name = "buffered_axi_lite_uart_smoke_seq");
        super.new(name);
    endfunction

    virtual task body();
        bit [31:0] rdata;
        // Write a known value to the first register (offset 0x00)
        axi_write(32'h00000000, 32'h00000000, 4'hF, "REG_0");
        // Read it back
        axi_read(32'h00000000, rdata, "REG_0");
        `uvm_info("SMOKE_SEQ",
            $sformatf("REG_0 readback = 0x%08h", rdata),
            UVM_MEDIUM)
    endtask

endclass