// ==============================================================
// File       : buffered_axi_lite_uart_coverage_subscriber.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : buffered_axi_lite_uart UVM coverage subscriber — functional coverage collection.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   axi_transaction_cg : cp_cmd, cp_addr, cp_resp, cross
//
// Dependencies:
//   buffered_axi_lite_uart_seq_item
//
// Portability    : Simulator-independent
// Impl. status   : generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
class buffered_axi_lite_uart_coverage_subscriber extends
    uvm_subscriber #(buffered_axi_lite_uart_seq_item);

    `uvm_component_utils(buffered_axi_lite_uart_coverage_subscriber)

    // Current transaction — updated before each sample() call.
    buffered_axi_lite_uart_seq_item item_s;

    covergroup axi_transaction_cg;

        // Confirms bidirectional bus traffic: both READ and WRITE must be hit.
        cp_cmd: coverpoint item_s.cmd {
            bins AXI_WRITE = {buffered_axi_lite_uart_seq_item::AXI_WRITE};
            bins AXI_READ  = {buffered_axi_lite_uart_seq_item::AXI_READ};
        }

        // One named bin per register — confirms each register was accessed.
        cp_addr: coverpoint item_s.addr[7:0] {
            bins addr_default = {default};
        }

        // Unhit SLVERR bin is informative — shows no error responses seen.
        cp_resp: coverpoint item_s.resp {
            bins OKAY   = {2'b00};
            bins SLVERR = {2'b10};
        }

        // Cross: confirms every register was both read and written where
        // access type permits. Unhit bins for RO/WO registers are expected.
        cp_cmd_x_addr: cross cp_cmd, cp_addr;

    endgroup

    function new(string name, uvm_component parent);
        super.new(name, parent);
        // Vivado requires embedded covergroups to be instantiated in new(),
        // not in build_phase (VRFC 10-8922).
        axi_transaction_cg = new();
    endfunction

    function void build_phase(uvm_phase phase);
        super.build_phase(phase);
    endfunction

    virtual function void write(buffered_axi_lite_uart_seq_item t);
        item_s = t;
        axi_transaction_cg.sample();
    endfunction

    function void report_phase(uvm_phase phase);
        `uvm_info("COV",
            $sformatf("axi_transaction_cg coverage: %.1f%%",
                axi_transaction_cg.get_coverage()),
            UVM_MEDIUM)
    endfunction

endclass