// ==============================================================
// File       : seq_RCOV009_int_status_timeout_int_status_rx_thresh.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-009: INT_STATUS.TIMEOUT && INT_STATUS.RX_THRESH — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 6 VSL step(s)) : Generated from Stimulus_VSL — COV-009
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-TO-005, UART-INT-002, UART-INT-008, UART-REG-014
// Stimulus strategy  : Set TIMEOUT_VAL non-zero, fill RX FIFO above RX_THRESH, then idle until timeout fires; verify both INT_STATUS.TIMEOUT and INT_STATUS.RX_THRESH set simultaneously.
// Boundary values    : RX FIFO > RX_THRESH (threshold set), then idle until timeout fires while threshold remains set

class seq_RCOV009_int_status_timeout_int_status_rx_thresh extends buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(seq_RCOV009_int_status_timeout_int_status_rx_thresh)

    function new(string name = "seq_RCOV009_int_status_timeout_int_status_rx_thresh");
        super.new(name);
    endfunction

    virtual task body();
        uvm_status_e status;
        uvm_reg_data_t rdata;
        // Step 1: WRITE
        reg_model.reg_0030.write(status, 0x0010, .parent(this));
        // Step 2: WRITE
        reg_model.reg_001c.write(status, 0x12, .parent(this));
        // Step 3: WRITE
        reg_model.reg_0034.write(status, 0x01, .parent(this));
        // Step 4: WRITE
        reg_model.reg_0000.write(status, 0x03, .parent(this));
        // Step 5: WRITE
        reg_model.reg_000c.write(status, 0xAB, .parent(this));
        // Step 6: POLL
        begin : poll_20
          int unsigned poll_count = 0;
          do begin
            reg_model.reg_0020.read(status, rdata, .parent(this));
            if ((rdata & 0x10) == 0x10) break;
            @(posedge vif.clk);
            poll_count++;
          end while (poll_count < 2000);
        end
    endtask : body

endclass