// ==============================================================
// File       : seq_RCOV008_int_status_overrun_int_status_rx_full.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-008: INT_STATUS.OVERRUN && INT_STATUS.RX_FULL — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 6 VSL step(s)) : Generated from Stimulus_VSL — COV-008
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-FIFO-007, UART-INT-005, UART-INT-006, UART-REG-018, UART-REG-024, UART-VER-005, UART-VER-010
// Stimulus strategy  : Fill RX FIFO to capacity then transmit additional byte to force overrun; verify overrun byte discarded and FIFO content unchanged.
// Boundary values    : RX FIFO at exactly G_FIFO_DEPTH, then one additional received byte

class seq_RCOV008_int_status_overrun_int_status_rx_full extends buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(seq_RCOV008_int_status_overrun_int_status_rx_full)

    function new(string name = "seq_RCOV008_int_status_overrun_int_status_rx_full");
        super.new(name);
    endfunction

    virtual task body();
        uvm_status_e status;
        uvm_reg_data_t rdata;
        // Step 1: WRITE
        reg_model.reg_0034.write(status, 0x01, .parent(this));
        // Step 2: WRITE
        reg_model.reg_001c.write(status, 0x48, .parent(this));
        // Step 3: WRITE
        reg_model.reg_0000.write(status, 0x03, .parent(this));
        // Step 4: WRITE
        reg_model.reg_000c.write(status, 0xFF, .parent(this));
        // Step 5: POLL
        begin : poll_04
          int unsigned poll_count = 0;
          do begin
            reg_model.reg_0004.read(status, rdata, .parent(this));
            if ((rdata & 0x08) == 0x08) break;
            @(posedge vif.clk);
            poll_count++;
          end while (poll_count < 2000);
        end
        // Step 6: READ
        reg_model.reg_0020.read(status, rdata, .parent(this));
    endtask : body

endclass