// ==============================================================
// File       : seq_RCOV017_frame_structural.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-017: FRAME_STRUCTURAL — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 5 VSL step(s)) : Generated from Stimulus_VSL — COV-017
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-FF-001, UART-FIFO-001, UART-IF-001, UART-IF-002, UART-IF-003, UART-IF-004, UART-IF-012, UART-IF-013, UART-IF-014, UART-PAR-001, UART-PAR-002, UART-PAR-009, UART-REG-032, UART-REG-033, UART-REG-034
// Stimulus strategy  : Structural inspection: verify 8-bit data frames transmitted and received, AXI data width=32, address width sufficient, single-beat transactions only.
// Boundary values    : 8-bit frames; FIFO depth=G_FIFO_DEPTH; AXI data width=32; no burst transactions

class seq_RCOV017_frame_structural extends buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(seq_RCOV017_frame_structural)

    function new(string name = "seq_RCOV017_frame_structural");
        super.new(name);
    endfunction

    virtual task body();
        uvm_status_e status;
        uvm_reg_data_t rdata;
        // Step 1: WRITE
        reg_model.reg_0028.write(status, 0x08, .parent(this));
        // Step 2: READ
        reg_model.reg_0028.read(status, rdata, .parent(this));
        `uvm_info(get_name(), $sformatf("Read 0x%0h, expect 0x%0h", rdata, 0x08), UVM_LOW)
        // Step 3: WRITE
        reg_model.reg_0034.write(status, 0x01, .parent(this));
        // Step 4: WRITE
        reg_model.reg_0000.write(status, 0x03, .parent(this));
        // Step 5: WRITE
        reg_model.reg_000c.write(status, 0xA5, .parent(this));
    endtask : body

endclass