// ==============================================================
// File       : seq_RCOV016_uart_en_control.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-016: UART_EN_CONTROL — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 6 VSL step(s)) : Generated from Stimulus_VSL — COV-016
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-EN-001, UART-EN-002, UART-EN-003, UART-EN-004, UART-EN-005, UART-EN-006, UART-REG-005, UART-REG-006, UART-REG-007, UART-REG-008
// Stimulus strategy  : Deassert UART_EN and verify TX/RX halt; then independently gate TX_EN and RX_EN with UART_EN=1 to verify path isolation; set LOOP_EN and verify loopback active.
// Boundary values    : UART_EN=0 (halt), TX_EN=0 (TX off/RX active), RX_EN=0 (RX off/TX active), LOOP_EN=1 with UART_EN=1

class seq_RCOV016_uart_en_control extends buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(seq_RCOV016_uart_en_control)

    function new(string name = "seq_RCOV016_uart_en_control");
        super.new(name);
    endfunction

    virtual task body();
        uvm_status_e status;
        uvm_reg_data_t rdata;
        // Step 1: WRITE
        reg_model.reg_0000.write(status, 0x01, .parent(this));
        // Step 2: READ
        reg_model.reg_0004.read(status, rdata, .parent(this));
        // Step 3: WRITE
        reg_model.reg_0000.write(status, 0x02, .parent(this));
        // Step 4: READ
        reg_model.reg_0004.read(status, rdata, .parent(this));
        // Step 5: WRITE
        reg_model.reg_0000.write(status, 0x03, .parent(this));
        // Step 6: READ
        reg_model.reg_0004.read(status, rdata, .parent(this));
    endtask : body

endclass