// ==============================================================
// File       : seq_RCOV002_ctrl_parity.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-002: CTRL.PARITY — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 6 VSL step(s)) : Generated from Stimulus_VSL — COV-002
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-FF-005, UART-FF-006, UART-FF-007, UART-FF-008, UART-FF-009, UART-REG-009, UART-VER-009
// Stimulus strategy  : All four parity modes (00/01/10/11) exercised independently in LOOP_EN loopback; inject parity error bit for odd and even modes.
// Boundary values    : 2'b00 (none), 2'b01 (odd+error inject), 2'b10 (even+error inject), 2'b11 (mark)

class seq_RCOV002_ctrl_parity extends buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(seq_RCOV002_ctrl_parity)

    function new(string name = "seq_RCOV002_ctrl_parity");
        super.new(name);
    endfunction

    virtual task body();
        uvm_status_e status;
        uvm_reg_data_t rdata;
        // Step 1: WRITE
        reg_model.reg_0034.write(status, 0x01, .parent(this));
        // Step 2: WRITE
        reg_model.reg_0024.write(status, 0x01, .parent(this));
        // Step 3: WRITE
        reg_model.reg_0000.write(status, 0x03, .parent(this));
        // Step 4: WRITE
        reg_model.reg_000c.write(status, 0x41, .parent(this));
        // Step 5: POLL
        begin : poll_04
          int unsigned poll_count = 0;
          do begin
            reg_model.reg_0004.read(status, rdata, .parent(this));
            if ((rdata & 0x02) == 0x02) break;
            @(posedge vif.clk);
            poll_count++;
          end while (poll_count < 1000);
        end
        // Step 6: READ
        reg_model.reg_0010.read(status, rdata, .parent(this));
        `uvm_info(get_name(), $sformatf("Read 0x%0h, expect 0x%0h", rdata, 0x41), UVM_LOW)
    endtask : body

endclass