// ==============================================================
// File       : seq_RCOV004_fifo_status_rx_level.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-004: FIFO_STATUS.RX_LEVEL — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 5 VSL step(s)) : Generated from Stimulus_VSL — COV-004
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-FIFO-004, UART-FIFO-005, UART-FIFO-007, UART-FIFO-009, UART-REG-019, UART-REG-034
// Stimulus strategy  : RX FIFO occupancy driven to 0, RX_THRESH-1, RX_THRESH, RX_THRESH+1, and G_FIFO_DEPTH to verify status flags and overrun discard.
// Boundary values    : 0 (RX_EMPTY), RX_THRESH-1, RX_THRESH, RX_THRESH+1 (interrupt fires), G_FIFO_DEPTH (full/overrun)

class seq_RCOV004_fifo_status_rx_level extends buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(seq_RCOV004_fifo_status_rx_level)

    function new(string name = "seq_RCOV004_fifo_status_rx_level");
        super.new(name);
    endfunction

    virtual task body();
        uvm_status_e status;
        uvm_reg_data_t rdata;
        // Step 1: WRITE
        reg_model.reg_0034.write(status, 0x01, .parent(this));
        // Step 2: WRITE
        reg_model.reg_0000.write(status, 0x03, .parent(this));
        // Step 3: WRITE
        reg_model.reg_000c.write(status, 0xAA, .parent(this));
        // Step 4: POLL
        begin : poll_04
          int unsigned poll_count = 0;
          do begin
            reg_model.reg_0004.read(status, rdata, .parent(this));
            if ((rdata & 0x02) == 0x02) break;
            @(posedge vif.clk);
            poll_count++;
          end while (poll_count < 1000);
        end
        // Step 5: READ
        reg_model.reg_0018.read(status, rdata, .parent(this));
    endtask : body

endclass