// ==============================================================
// File       : seq_RCOV012_axi_write_order.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-012: AXI_WRITE_ORDER — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 4 VSL step(s)) : Generated from Stimulus_VSL — COV-012
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-IF-005, UART-VER-006
// Stimulus strategy  : Issue AXI write with AWVALID first then WVALID, then repeat with WVALID first then AWVALID; verify correct response in both orderings.
// Boundary values    : AWVALID_FIRST ordering, WVALID_FIRST ordering

class seq_RCOV012_axi_write_order extends buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(seq_RCOV012_axi_write_order)

    function new(string name = "seq_RCOV012_axi_write_order");
        super.new(name);
    endfunction

    virtual task body();
        uvm_status_e status;
        uvm_reg_data_t rdata;
        // Step 1: WRITE
        reg_model.reg_002c.write(status, 0xA5A5, .parent(this));
        // Step 2: READ
        reg_model.reg_002c.read(status, rdata, .parent(this));
        `uvm_info(get_name(), $sformatf("Read 0x%0h, expect 0x%0h", rdata, 0xA5A5), UVM_LOW)
        // Step 3: WRITE
        reg_model.reg_002c.write(status, 0x5A5A, .parent(this));
        // Step 4: READ
        reg_model.reg_002c.read(status, rdata, .parent(this));
        `uvm_info(get_name(), $sformatf("Read 0x%0h, expect 0x%0h", rdata, 0x5A5A), UVM_LOW)
    endtask : body

endclass