// ==============================================================
// File       : seq_RCOV013_baud_tuning_write_while_enabled.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-013: BAUD_TUNING_WRITE_WHILE_ENABLED — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 4 VSL step(s)) : Generated from Stimulus_VSL — COV-013
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-REG-028, UART-VER-007
// Stimulus strategy  : Assert UART_EN, write a new value to BAUD_TUNING, read back and verify original value unchanged; confirms silent-ignore while enabled.
// Boundary values    : UART_EN=1, write new value, readback must equal original value

class seq_RCOV013_baud_tuning_write_while_enabled extends buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(seq_RCOV013_baud_tuning_write_while_enabled)

    function new(string name = "seq_RCOV013_baud_tuning_write_while_enabled");
        super.new(name);
    endfunction

    virtual task body();
        uvm_status_e status;
        uvm_reg_data_t rdata;
        // Step 1: WRITE
        reg_model.reg_0008.write(status, 0x000010D6, .parent(this));
        // Step 2: WRITE
        reg_model.reg_0000.write(status, 0x03, .parent(this));
        // Step 3: WRITE
        reg_model.reg_0008.write(status, 0x00000001, .parent(this));
        // Step 4: READ
        reg_model.reg_0008.read(status, rdata, .parent(this));
    endtask : body

endclass