// ==============================================================
// File       : tb_top.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : tb_top — top-level testbench module; DUT instantiation, clock/reset, UVM run_test().
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   DUT instantiation  : All ports connected via interface
//   Clock/reset        : 100 MHz clock; synchronous active-low reset
//   UVM config_db      : Virtual interface registration
//
// Dependencies:
//   uvm_pkg
//   buffered_axi_lite_uart_pkg
//   buffered_axi_lite_uart_if
//
// Portability    : Vivado/Questa/Icarus
// Impl. status   : generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
`timescale 1ns/1ps
module tb_top;
    import uvm_pkg::*;
    import buffered_axi_lite_uart_pkg::*;
    `include "uvm_macros.svh"

    // Free-running clock
    logic clk;
    initial clk = 1'b0;
    always #5 clk = ~clk;

    // Interface instance
    buffered_axi_lite_uart_if intf(.clk(clk));

    // DUT instantiation
    buffered_axi_lite_uart dut (
        .axi_aclk(intf.axi_aclk),
        .axi_aresetn(intf.axi_aresetn),
        .s_axi_awvalid(intf.s_axi_awvalid),
        .s_axi_awready(intf.s_axi_awready),
        .s_axi_awaddr(intf.s_axi_awaddr),
        .s_axi_awprot(intf.s_axi_awprot),
        .s_axi_wvalid(intf.s_axi_wvalid),
        .s_axi_wready(intf.s_axi_wready),
        .s_axi_wdata(intf.s_axi_wdata),
        .s_axi_wstrb(intf.s_axi_wstrb),
        .s_axi_bvalid(intf.s_axi_bvalid),
        .s_axi_bready(intf.s_axi_bready),
        .s_axi_bresp(intf.s_axi_bresp),
        .s_axi_arvalid(intf.s_axi_arvalid),
        .s_axi_arready(intf.s_axi_arready),
        .s_axi_araddr(intf.s_axi_araddr),
        .s_axi_arprot(intf.s_axi_arprot),
        .s_axi_rvalid(intf.s_axi_rvalid),
        .s_axi_rready(intf.s_axi_rready),
        .s_axi_rdata(intf.s_axi_rdata),
        .s_axi_rresp(intf.s_axi_rresp),
        .uart_tx(intf.uart_tx),
        .uart_rx(intf.uart_rx),
        .irq(intf.irq)
    );

    // clk drives intf directly via the interface port

    initial begin
        // Initialise all interface signals
        intf.axi_aclk = '0;
        intf.axi_aresetn = '0;
        intf.s_axi_awvalid = '0;
        intf.s_axi_awready = '0;
        intf.s_axi_awaddr = '0;
        intf.s_axi_awprot = '0;
        intf.s_axi_wvalid = '0;
        intf.s_axi_wready = '0;
        intf.s_axi_wdata = '0;
        intf.s_axi_wstrb = '0;
        intf.s_axi_bvalid = '0;
        intf.s_axi_bready = '0;
        intf.s_axi_bresp = '0;
        intf.s_axi_arvalid = '0;
        intf.s_axi_arready = '0;
        intf.s_axi_araddr = '0;
        intf.s_axi_arprot = '0;
        intf.s_axi_rvalid = '0;
        intf.s_axi_rready = '0;
        intf.s_axi_rdata = '0;
        intf.s_axi_rresp = '0;
        intf.uart_tx = '0;
        intf.uart_rx = 1'b1;
        intf.irq = '0;
        // Hold reset for 10 clock cycles then deassert
                intf.rst_n = 1'b0;
        repeat (10) @(posedge clk);
                intf.rst_n = 1'b1;
    end

    // Pass virtual interface to UVM config_db
    initial begin
        uvm_config_db #(virtual buffered_axi_lite_uart_if)::set(null, "uvm_test_top.*", "vif", intf);
        run_test();
    end

    // Waveform dump
    initial begin
        $dumpfile("tb_top.vcd");
        $dumpvars(0, tb_top);
    end

endmodule