// ==============================================================
// File       : buffered_axi_lite_uart_env.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : buffered_axi_lite_uart UVM environment — top-level env instantiating agent, scoreboard, and coverage.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   connect_phase      : Wire monitor AP to scoreboard and coverage subscriber
//
// Dependencies:
//   buffered_axi_lite_uart_agent
//   buffered_axi_lite_uart_scoreboard
//   buffered_axi_lite_uart_coverage_subscriber
//
// Portability    : Simulator-independent
// Impl. status   : generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
class buffered_axi_lite_uart_env extends uvm_env;
    `uvm_component_utils(buffered_axi_lite_uart_env)

    buffered_axi_lite_uart_agent                   agent;
    buffered_axi_lite_uart_scoreboard              sb;
    buffered_axi_lite_uart_coverage_subscriber     cov;

    function new(string name, uvm_component parent);
        super.new(name, parent);
    endfunction

    function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        agent = buffered_axi_lite_uart_agent::type_id::create("agent", this);
        sb    = buffered_axi_lite_uart_scoreboard::type_id::create("sb", this);
        cov   = buffered_axi_lite_uart_coverage_subscriber::type_id::create("cov", this);
    endfunction

    function void connect_phase(uvm_phase phase);
        agent.mon.ap.connect(sb.analysis_export);
        agent.mon.ap.connect(cov.analysis_export);
    endfunction

endclass