// ==============================================================
// File       : buffered_axi_lite_uart_scoreboard.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : buffered_axi_lite_uart UVM scoreboard — AXI-Lite register shadow model and response checker.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   _init_shadow       : Populate shadow from VPR register map
//   write()            : Compare read data against shadow; check write responses
//
// Dependencies:
//   buffered_axi_lite_uart_seq_item
//   vplan register map
//
// Portability    : Simulator-independent
// Impl. status   : generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
class buffered_axi_lite_uart_scoreboard extends uvm_scoreboard;
    `uvm_component_utils(buffered_axi_lite_uart_scoreboard)

    uvm_analysis_imp #(buffered_axi_lite_uart_seq_item,
                       buffered_axi_lite_uart_scoreboard) analysis_export;

    // Shadow register model — RW registers only.
    // RO and WO registers are not predicted here.
    local bit [31:0] shadow [bit [31:0]];

    // Running error count reported in check_phase.
    local int error_count;

    function new(string name, uvm_component parent);
        super.new(name, parent);
        error_count = 0;
    endfunction

    function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        analysis_export = new("analysis_export", this);
        _init_shadow();
    endfunction

    // Pre-load RW register reset values.
    local function void _init_shadow();
        `uvm_warning("SB",
            "Shadow register map not available — scoreboard checks disabled")
    endfunction

    // Apply a write to the shadow, honouring wstrb byte-enable masking.
    local function void _apply_write(
        bit [31:0] addr,
        bit [31:0] wdata,
        bit [3:0]  wstrb
    );
        for (int b = 0; b < 4; b++) begin
            if (wstrb[b])
                shadow[addr][b*8 +: 8] = wdata[b*8 +: 8];
        end
    endfunction

    function void write(buffered_axi_lite_uart_seq_item item);
        if (item.cmd === buffered_axi_lite_uart_seq_item::AXI_WRITE) begin

            if (item.resp !== 2'b00) begin
                error_count++;
                `uvm_error("SB", $sformatf(
                    "write response not OKAY — addr=0x%08h resp=%02b",
                    item.addr, item.resp))
            end

            if (shadow.exists(item.addr))
                _apply_write(item.addr, item.wdata, item.wstrb);

        end else begin  // AXI_READ

            if (item.resp !== 2'b00) begin
                error_count++;
                `uvm_error("SB", $sformatf(
                    "read response not OKAY — addr=0x%08h resp=%02b",
                    item.addr, item.resp))
            end

            if (shadow.exists(item.addr)) begin
                if (item.rdata !== shadow[item.addr]) begin
                    error_count++;
                    `uvm_error("SB", $sformatf(
                        "register readback mismatch — addr=0x%08h expected=0x%08h actual=0x%08h",
                        item.addr, shadow[item.addr], item.rdata))
                end
            end
        end
    endfunction

    function void check_phase(uvm_phase phase);
        `uvm_info("SB", $sformatf(
            "Scoreboard check_phase: %0d error(s)", error_count), UVM_MEDIUM)
    endfunction

endclass