// ==============================================================
// File       : seq_RCOV002_ctrl_parity.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-002: CTRL.PARITY — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 6 VSL step(s)) : Generated from Stimulus_VSL — COV-002
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-FF-005, UART-FF-006, UART-FF-007, UART-FF-008, UART-FF-009, UART-REG-009, UART-VER-009
// Stimulus strategy  : All four parity modes (00/01/10/11) exercised independently in LOOP_EN loopback; inject parity error bit for odd and even modes.
// Boundary values    : 2'b00 (none), 2'b01 (odd+error inject), 2'b10 (even+error inject), 2'b11 (mark)

class seq_RCOV002_ctrl_parity extends axi4_lite_base_seq;

    `uvm_object_utils(seq_RCOV002_ctrl_parity)

    function new(string name = "seq_RCOV002_ctrl_parity");
        super.new(name);
    endfunction

    virtual task body();
        uvm_reg_data_t rdata;
        // Step 1: WRITE
        reg_write(reg_model.LOOPBACK, 0x01);
        // Step 2: WRITE
        reg_write(reg_model.PARITY, 0x01);
        // Step 3: WRITE
        reg_write(reg_model.CTRL, 0x03);
        // Step 4: WRITE
        reg_write(reg_model.TX_DATA, 0x41);
        // Step 5: POLL
        reg_poll(reg_model.STATUS, 0x02, 0x02, 1000);
        // Step 6: READ
        reg_read(reg_model.RX_DATA, rdata);
        `uvm_info(get_name(), $sformatf("Read 0x%0h, expect 0x%0h", rdata, 0x41), UVM_LOW)
    endtask : body

endclass