// ==============================================================
// File       : seq_RCOV004_fifo_status_rx_level.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-004: FIFO_STATUS.RX_LEVEL — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 5 VSL step(s)) : Generated from Stimulus_VSL — COV-004
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-FIFO-004, UART-FIFO-005, UART-FIFO-007, UART-FIFO-009, UART-REG-019, UART-REG-034
// Stimulus strategy  : RX FIFO occupancy driven to 0, RX_THRESH-1, RX_THRESH, RX_THRESH+1, and G_FIFO_DEPTH to verify status flags and overrun discard.
// Boundary values    : 0 (RX_EMPTY), RX_THRESH-1, RX_THRESH, RX_THRESH+1 (interrupt fires), G_FIFO_DEPTH (full/overrun)

class seq_RCOV004_fifo_status_rx_level extends axi4_lite_base_seq;

    `uvm_object_utils(seq_RCOV004_fifo_status_rx_level)

    function new(string name = "seq_RCOV004_fifo_status_rx_level");
        super.new(name);
    endfunction

    virtual task body();
        uvm_reg_data_t rdata;
        // Step 1: WRITE
        reg_write(reg_model.LOOPBACK, 0x01);
        // Step 2: WRITE
        reg_write(reg_model.CTRL, 0x03);
        // Step 3: WRITE
        reg_write(reg_model.TX_DATA, 0xAA);
        // Step 4: POLL
        reg_poll(reg_model.STATUS, 0x02, 0x02, 1000);
        // Step 5: READ
        reg_read(reg_model.RX_FIFO, rdata);
    endtask : body

endclass