# ==============================================================
# File       : build.tcl
# Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
# Copyright  : Copyright (c) 2026 BelTech Systems LLC
# License    : MIT License — see LICENSE for details
# ==============================================================
# Brief      : buffered_axi_lite_uart Vivado/XSIM build and run script — three-file compile model per STD-003.
# Document   : BelTech-STD-003 Rev 1
# Tool       : Vivado 2024.x / XSIM
#
# Usage:
#   vivado -mode tcl -source build.tcl
#
# Impl. status   : generated
#
# History:
#   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
# ==============================================================
set DESIGN   buffered_axi_lite_uart
set SNAPSHOT balu_sim_snapshot

# Path anchors — all relative to this script's location (scripts/vivado)
set REPO_ROOT [file normalize [file join [file dirname [info script]] ../../../../../]]
set SIM_LIB   [file join $REPO_ROOT sim/lib]
set TB_DIR    [file join $REPO_ROOT output/buffered_axi_lite_uart_ral_session2/tb]
set RTL_DIR   [file join $REPO_ROOT ip/buffered_axi_lite_uart/rtl]

proc run_cmd {cmd} {
    if {[catch {exec {*}$cmd >@stdout 2>@stderr} msg]} {
        puts "ERROR: Command failed:"
        puts "  $cmd"
        puts $msg
        exit 1
    }
}

# ── Step 1: Compile sim/lib BFM and RAL library ──────────────────────────────
puts "--- Step 1: Compiling sim/lib ---"
run_cmd [list xvlog --sv --uvm_version 1.2 -L uvm --work work \
    --include $REPO_ROOT \
    [file join $SIM_LIB bfm/axi4_lite_if.sv] \
    [file join $SIM_LIB bfm/axi4_lite_seq_item.sv] \
    [file join $SIM_LIB bfm/axi4_lite_master_bfm.sv] \
    [file join $SIM_LIB ral/axi4_lite_reg_adapter.sv] \
    [file join $SIM_LIB ral/axi4_lite_predictor.sv] \
    [file join $SIM_LIB ral/balu_reg_model.sv] \
    [file join $SIM_LIB seq/axi4_lite_base_seq.sv] \
    [file join $SIM_LIB pkg/bfm_pkg.sv]]

# ── Step 2: Compile DUT ───────────────────────────────────────────────────────
puts "--- Step 2: Compiling DUT ---"
# NOTE: User must provide RTL source path before running.
# Uncomment ONE of the lines below depending on RTL language.
# BALU is VHDL — use xvhdl not xvlog for RTL compilation:
# xvhdl --2008 --work work [glob $RTL_DIR/*.vhd]
# For SV RTL:
# xvlog --sv --work work [glob $RTL_DIR/*.sv]

# ── Step 3: Compile TB ────────────────────────────────────────────────────────
puts "--- Step 3: Compiling TB ---"
run_cmd [list xvlog --sv --uvm_version 1.2 -L uvm --work work \
    --include $TB_DIR \
    --include $REPO_ROOT \
    [file join $TB_DIR ${DESIGN}_pkg.sv] \
    [file join $TB_DIR tb_top.sv]]

# ── Step 4: Elaborate ─────────────────────────────────────────────────────────
puts "--- Step 4: Elaborating ---"
run_cmd [list xelab -L uvm \
    work.tb_top \
    -s $SNAPSHOT \
    -timescale 1ns/1ps \
    -debug typical]

# ── Step 5: Simulate ──────────────────────────────────────────────────────────
puts "--- Step 5: Simulating ---"
run_cmd [list xsim $SNAPSHOT \
    -testplusarg UVM_TESTNAME=${DESIGN}_smoke_test \
    -testplusarg UVM_VERBOSITY=UVM_LOW \
    -runall \
    -log xsim.log]

puts "Simulation complete. Log: xsim.log"
