// ==============================================================
// File       : buffered_axi_lite_uart_base_seq.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : buffered_axi_lite_uart base sequence — axi_write() and axi_read() helper tasks.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   axi_write          : Drive a write transaction
//   axi_read           : Drive a read transaction
//
// Dependencies:
//   buffered_axi_lite_uart_seq_item
//   buffered_axi_lite_uart_sequencer
//
// Portability    : Simulator-independent
// Impl. status   : generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
class buffered_axi_lite_uart_base_seq extends
    uvm_sequence #(buffered_axi_lite_uart_seq_item);

    `uvm_object_utils(buffered_axi_lite_uart_base_seq)

    function new(string name = "buffered_axi_lite_uart_base_seq");
        super.new(name);
    endfunction

    // Convenience task: perform one AXI-Lite write and wait for BVALID.
    // The driver handles handshaking; this task just creates and sends
    // the item.
    virtual task axi_write(input bit [31:0] addr,
                           input bit [31:0] data,
                           input bit [3:0]  strb     = 4'hF,
                           input string     reg_name = "");
        buffered_axi_lite_uart_seq_item item;
        item = buffered_axi_lite_uart_seq_item::type_id::create("item");
        start_item(item);
        item.set_write(addr, data, strb, reg_name);
        finish_item(item);
    endtask

    // Convenience task: perform one AXI-Lite read.
    virtual task axi_read(input  bit [31:0] addr,
                          output bit [31:0] rdata,
                          input  string     reg_name = "");
        buffered_axi_lite_uart_seq_item item;
        item = buffered_axi_lite_uart_seq_item::type_id::create("item");
        start_item(item);
        item.set_read(addr, reg_name);
        finish_item(item);
        rdata = item.rdata;
    endtask

endclass