// ==============================================================
// File       : seq_RCOV018_readonly_ignore.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-018: READONLY_IGNORE — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (SEQ_PENDING) : Stub — see VPR COV-018 for implementation guidance
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : stub
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-IF-010, UART-IF-011, UART-REG-002, UART-REG-003, UART-REG-011, UART-REG-012, UART-REG-025, UART-REG-038, UART-REG-042, UART-REG-049, UART-REG-052
// Stimulus strategy  : Write to each read-only register (STATUS, FIFO_STATUS, INT_STATUS, INT_CLEAR, TX_DATA reads, RX_DATA writes); read back and verify state unchanged.
// Boundary values    : Write all-ones to each RO register; compare pre- and post-write readback for each

class seq_RCOV018_readonly_ignore extends buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(seq_RCOV018_readonly_ignore)

    function new(string name = "seq_RCOV018_readonly_ignore");
        super.new(name);
    endfunction

    virtual task body();
        `uvm_info("SEQ_PENDING",
            "seq_RCOV018_readonly_ignore: body not yet implemented — see VPR COV-018",
            UVM_MEDIUM)
    endtask

endclass