// ==============================================================
// File       : buffered_axi_lite_uart_seqr.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : buffered_axi_lite_uart UVM sequencer.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
//   2026-04-19  pssgen  RAL Session 3: use within-package axi4_lite_seq_item
// ==============================================================
class buffered_axi_lite_uart_sequencer extends uvm_sequencer #(axi4_lite_seq_item);
    `uvm_component_utils(buffered_axi_lite_uart_sequencer)

    function new(string name, uvm_component parent);
        super.new(name, parent);
    endfunction
endclass
