// ==============================================================
// File       : buffered_axi_lite_uart_seqr.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : buffered_axi_lite_uart UVM sequencer — arbitrates sequence item flow to driver.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   Sequencer          : uvm_sequencer parameterised on buffered_axi_lite_uart_seq_item
//
// Dependencies:
//   buffered_axi_lite_uart_seq_item
//
// Portability    : Simulator-independent
// Impl. status   : generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
class buffered_axi_lite_uart_sequencer extends uvm_sequencer #(buffered_axi_lite_uart_seq_item);
    `uvm_component_utils(buffered_axi_lite_uart_sequencer)

    function new(string name, uvm_component parent);
        super.new(name, parent);
    endfunction
endclass