// ==============================================================
// File       : buffered_axi_lite_uart_scoreboard.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : buffered_axi_lite_uart UVM scoreboard — AXI-Lite response checker.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
//   2026-04-19  pssgen  RAL Session 3: within-package template parameter
// ==============================================================
class buffered_axi_lite_uart_scoreboard extends uvm_scoreboard;
    `uvm_component_utils(buffered_axi_lite_uart_scoreboard)

    uvm_analysis_imp #(axi4_lite_seq_item,
                       buffered_axi_lite_uart_scoreboard) analysis_export;

    local bit [31:0] shadow [bit [31:0]];
    local int error_count;

    function new(string name, uvm_component parent);
        super.new(name, parent);
        error_count = 0;
    endfunction

    function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        analysis_export = new("analysis_export", this);
        `uvm_warning("SB",
            "Shadow register map not available — scoreboard checks disabled")
    endfunction

    local function void _apply_write(
        bit [31:0] addr, bit [31:0] wdata, bit [3:0] wstrb);
        for (int b = 0; b < 4; b++)
            if (wstrb[b]) shadow[addr][b*8 +: 8] = wdata[b*8 +: 8];
    endfunction

    function void write(axi4_lite_seq_item item);
        if (item.kind === axi4_lite_seq_item::WRITE) begin
            if (item.resp !== 2'b00) begin
                `uvm_info("SB", $sformatf(
                    "write SLVERR — addr=0x%08h resp=%02b", item.addr, item.resp), UVM_LOW)
            end
            if (shadow.exists(item.addr))
                _apply_write(item.addr, item.data, item.strb);
        end else begin
            if (item.resp !== 2'b00) begin
                `uvm_info("SB", $sformatf(
                    "read SLVERR — addr=0x%08h resp=%02b", item.addr, item.resp), UVM_LOW)
            end
            if (shadow.exists(item.addr) && item.data !== shadow[item.addr]) begin
                error_count++;
                `uvm_error("SB", $sformatf(
                    "readback mismatch — addr=0x%08h exp=0x%08h got=0x%08h",
                    item.addr, shadow[item.addr], item.data))
            end
        end
    endfunction

    function void check_phase(uvm_phase phase);
        `uvm_info("SB", $sformatf(
            "Scoreboard check_phase: %0d error(s)", error_count), UVM_MEDIUM)
    endfunction

endclass
