// ==============================================================
// File       : buffered_axi_lite_uart_monitor.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : buffered_axi_lite_uart UVM monitor — observes balu_axi_if
//              and publishes axi4_lite_seq_item via uvm_analysis_port.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
//   2026-04-19  pssgen  RAL Session 3: within-package template parameter
// ==============================================================
class buffered_axi_lite_uart_monitor extends uvm_monitor;
    `uvm_component_utils(buffered_axi_lite_uart_monitor)

    virtual balu_axi_if                      vif;
    uvm_analysis_port #(axi4_lite_seq_item)   ap;

    function new(string name, uvm_component parent);
        super.new(name, parent);
    endfunction

    function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        ap = new("ap", this);
        if (!uvm_config_db #(virtual balu_axi_if)::get(
                this, "", "vif", vif))
            `uvm_fatal("NO_VIF",
                "buffered_axi_lite_uart_monitor: vif not found in config_db")
    endfunction

    task run_phase(uvm_phase phase);
        axi4_lite_seq_item item;
        logic [31:0] aw_addr_lat_s;
        logic [31:0] wd_data_lat_s;
        logic [3:0]  wd_strb_lat_s;
        logic [31:0] ar_addr_lat_s;

        @(posedge vif.ACLK iff vif.ARESETn === 1'b1);

        forever begin
            @(posedge vif.ACLK);

            if (vif.AWVALID === 1'b1 && vif.AWREADY === 1'b1)
                aw_addr_lat_s = vif.AWADDR;

            if (vif.WVALID === 1'b1 && vif.WREADY === 1'b1) begin
                wd_data_lat_s = vif.WDATA;
                wd_strb_lat_s = vif.WSTRB;
            end

            if (vif.BVALID === 1'b1 && vif.BREADY === 1'b1) begin
                item = axi4_lite_seq_item::type_id::create("mon_wr");
                item.kind = axi4_lite_seq_item::WRITE;
                item.addr = aw_addr_lat_s;
                item.data = wd_data_lat_s;
                item.strb = wd_strb_lat_s;
                item.resp = vif.BRESP;
                ap.write(item);
            end

            if (vif.ARVALID === 1'b1 && vif.ARREADY === 1'b1)
                ar_addr_lat_s = vif.ARADDR;

            if (vif.RVALID === 1'b1 && vif.RREADY === 1'b1) begin
                item = axi4_lite_seq_item::type_id::create("mon_rd");
                item.kind = axi4_lite_seq_item::READ;
                item.addr = ar_addr_lat_s;
                item.data = vif.RDATA;
                item.resp = vif.RRESP;
                ap.write(item);
            end
        end
    endtask

endclass
