// ==============================================================
// File       : buffered_axi_lite_uart_base_seq.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : buffered_axi_lite_uart base sequence — axi_write(), axi_read(),
//              and axi_poll() helpers. Uses within-package axi4_lite_seq_item
//              as template parameter to avoid xelab 2025.1 cross-pkg crash.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
//   2026-04-19  pssgen  RAL Session 3: within-package template + axi_poll
// ==============================================================
class buffered_axi_lite_uart_base_seq extends
    uvm_sequence #(axi4_lite_seq_item);

    `uvm_object_utils(buffered_axi_lite_uart_base_seq)

    // Interface handle for clock-wait tasks (populated from config_db in pre_start).
    virtual balu_axi_if vif;

    function new(string name = "buffered_axi_lite_uart_base_seq");
        super.new(name);
    endfunction

    task pre_start();
        if (!uvm_config_db #(virtual balu_axi_if)::get(
                null, get_full_name(), "vif", vif))
            `uvm_fatal(get_name(), "pre_start: virtual balu_axi_if not in config_db")
    endtask

    virtual task axi_write(input bit [31:0] addr,
                           input bit [31:0] data,
                           input bit [3:0]  strb     = 4'hF,
                           input string     reg_name = "");
        axi4_lite_seq_item item;
        item = axi4_lite_seq_item::type_id::create("item");
        start_item(item);
        item.kind = axi4_lite_seq_item::WRITE;
        item.addr = addr;
        item.data = data;
        item.strb = strb;
        finish_item(item);
    endtask

    virtual task axi_read(input  bit [31:0] addr,
                          output bit [31:0] rdata,
                          input  string     reg_name = "");
        axi4_lite_seq_item item;
        item = axi4_lite_seq_item::type_id::create("item");
        start_item(item);
        item.kind = axi4_lite_seq_item::READ;
        item.addr = addr;
        item.strb = 4'h0;
        finish_item(item);
        rdata = item.data;
    endtask

    // Pulse ARESETn_seq low for `cycles` clocks then release; restores DUT
    // to power-on state (BAUD_TUNING, FIFOs, CTRL all reset to defaults).
    virtual task reset_dut(int unsigned cycles = 10);
        vif.ARESETn_seq = 1'b0;
        repeat(cycles) @(posedge vif.ACLK);
        vif.ARESETn_seq = 1'b1;
        @(posedge vif.ACLK);
    endtask

    // Poll addr until (rdata & mask) == expected, or timeout cycles elapsed.
    virtual task axi_poll(input bit [31:0] addr,
                          input bit [31:0] mask,
                          input bit [31:0] expected,
                          input int        timeout_cycles = 1000);
        bit [31:0] rdata;
        int cycles;
        cycles = 0;
        do begin
            axi_read(addr, rdata);
            if ((rdata & mask) === expected) return;
            @(posedge vif.ACLK);
            cycles++;
        end while (cycles < timeout_cycles);
        `uvm_warning(get_name(), $sformatf(
            "axi_poll timeout — addr=0x%08h mask=0x%08h exp=0x%08h got=0x%08h",
            addr, mask, expected, rdata))
    endtask

endclass
