// ==============================================================
// File       : buffered_axi_lite_uart_env.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : buffered_axi_lite_uart UVM environment.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
//   2026-04-19  pssgen  RAL Session 3: RAL wiring, within-pkg types
// ==============================================================
class buffered_axi_lite_uart_env extends uvm_env;
    `uvm_component_utils(buffered_axi_lite_uart_env)

    buffered_axi_lite_uart_agent                   agent;
    buffered_axi_lite_uart_scoreboard              sb;
    buffered_axi_lite_uart_coverage_subscriber     cov;
    balu_reg_model         reg_model;
    axi4_lite_reg_adapter  adapter;
    // axi4_lite_predictor deferred: parameterized class crashes xelab 2025.1

    function new(string name, uvm_component parent);
        super.new(name, parent);
    endfunction

    function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        agent = buffered_axi_lite_uart_agent::type_id::create("agent", this);
        sb    = buffered_axi_lite_uart_scoreboard::type_id::create("sb", this);
        cov   = buffered_axi_lite_uart_coverage_subscriber::type_id::create("cov", this);
        reg_model = balu_reg_model::type_id::create("reg_model", this);
        reg_model.build();
        reg_model.reset();
        adapter   = axi4_lite_reg_adapter::type_id::create("adapter", this);
    endfunction

    function void connect_phase(uvm_phase phase);
        agent.mon.ap.connect(sb.analysis_export);
        agent.mon.ap.connect(cov.analysis_export);
        reg_model.default_map.set_sequencer(agent.seqr, adapter);
        reg_model.default_map.set_auto_predict(1);
        uvm_config_db #(balu_reg_model)::set(this, "*", "reg_model", reg_model);
    endfunction

endclass
