// ==============================================================
// File       : buffered_axi_lite_uart_coverage_subscriber.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : buffered_axi_lite_uart UVM coverage subscriber.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
//   2026-04-19  pssgen  RAL Session 3: within-package template parameter
// ==============================================================
class buffered_axi_lite_uart_coverage_subscriber extends
    uvm_subscriber #(axi4_lite_seq_item);

    `uvm_component_utils(buffered_axi_lite_uart_coverage_subscriber)

    axi4_lite_seq_item item_s;

    covergroup axi_transaction_cg;
        cp_kind: coverpoint item_s.kind {
            bins WRITE = {axi4_lite_seq_item::WRITE};
            bins READ  = {axi4_lite_seq_item::READ};
        }
        cp_addr: coverpoint item_s.addr[7:0] {
            bins addr_CTRL      = {8'h00};
            bins addr_STATUS    = {8'h04};
            bins addr_BAUD      = {8'h08};
            bins addr_TX_DATA   = {8'h0C};
            bins addr_RX_DATA   = {8'h10};
            bins addr_TX_FIFO   = {8'h14};
            bins addr_RX_FIFO   = {8'h18};
            bins addr_IER       = {8'h1C};
            bins addr_ISR       = {8'h20};
            bins addr_PARITY    = {8'h24};
            bins addr_FRAME     = {8'h28};
            bins addr_SCRATCH   = {8'h2C};
        }
        cp_resp: coverpoint item_s.resp {
            bins OKAY   = {2'b00};
            bins SLVERR = {2'b10};
        }
        cp_kind_x_addr: cross cp_kind, cp_addr;
    endgroup

    function new(string name, uvm_component parent);
        super.new(name, parent);
        axi_transaction_cg = new();
    endfunction

    function void build_phase(uvm_phase phase);
        super.build_phase(phase);
    endfunction

    virtual function void write(axi4_lite_seq_item t);
        item_s = t;
        axi_transaction_cg.sample();
    endfunction

    function void report_phase(uvm_phase phase);
        `uvm_info("COV",
            $sformatf("axi_transaction_cg coverage: %.1f%%",
                axi_transaction_cg.get_coverage()),
            UVM_LOW)
    endfunction

endclass
