// ==============================================================
// File       : buffered_axi_lite_uart_agent.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : buffered_axi_lite_uart UVM agent — instantiates driver, monitor, and sequencer.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   build_phase        : Create drv/mon/seqr
//   connect_phase      : Wire seq_item_port to seq_item_export
//
// Dependencies:
//   buffered_axi_lite_uart_driver
//   buffered_axi_lite_uart_monitor
//   buffered_axi_lite_uart_sequencer
//
// Portability    : Simulator-independent
// Impl. status   : generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
class buffered_axi_lite_uart_agent extends uvm_agent;
    `uvm_component_utils(buffered_axi_lite_uart_agent)

    buffered_axi_lite_uart_driver     drv;
    buffered_axi_lite_uart_monitor    mon;
    buffered_axi_lite_uart_sequencer  seqr;

    function new(string name, uvm_component parent);
        super.new(name, parent);
    endfunction

    function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        drv  = buffered_axi_lite_uart_driver::type_id::create("drv",  this);
        mon  = buffered_axi_lite_uart_monitor::type_id::create("mon", this);
        seqr = buffered_axi_lite_uart_sequencer::type_id::create("seqr", this);
    endfunction

    function void connect_phase(uvm_phase phase);
        drv.seq_item_port.connect(seqr.seq_item_export);
        // mon.ap is connected to sb and cov in env.sv connect_phase
    endfunction

endclass