// ==============================================================
// File       : buffered_axi_lite_uart_pkg.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : buffered_axi_lite_uart UVM package.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Portability    : Simulator-independent
// Impl. status   : generated-ral
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
//   2026-04-19  pssgen  RAL Session 3: RAL classes inlined, balu_axi_if non-param
// ==============================================================
package buffered_axi_lite_uart_pkg;
    import uvm_pkg::*;
    `include "uvm_macros.svh"

    // RAL and BFM infrastructure included directly (no bfm_pkg import).
    // balu_axi_if is non-parameterized to avoid xelab 2025.1 virtual-interface crash.
    `include "sim/lib/bfm/axi4_lite_seq_item.sv"
    `include "sim/lib/ral/axi4_lite_reg_adapter.sv"
    `include "sim/lib/ral/balu_reg_model.sv"

    // TB classes in strict dependency order
    `include "buffered_axi_lite_uart_seq_item.sv"
    `include "buffered_axi_lite_uart_seqr.sv"
    `include "buffered_axi_lite_uart_driver.sv"
    `include "buffered_axi_lite_uart_monitor.sv"
    `include "buffered_axi_lite_uart_scoreboard.sv"
    `include "buffered_axi_lite_uart_coverage_subscriber.sv"
    `include "buffered_axi_lite_uart_base_seq.sv"
    `include "buffered_axi_lite_uart_smoke_seq.sv"
    `include "seq_RCOV001_baud_tuning.sv"
    `include "seq_RCOV002_ctrl_parity.sv"
    `include "seq_RCOV003_ctrl_stop_bits.sv"
    `include "seq_RCOV004_fifo_status_rx_level.sv"
    `include "seq_RCOV005_fifo_status_tx_level.sv"
    `include "seq_RCOV006_timeout_val.sv"
    `include "seq_RCOV007_int_status_each_bit_independently.sv"
    `include "seq_RCOV008_int_status_overrun_int_status_rx_full.sv"
    `include "seq_RCOV009_int_status_timeout_int_status_rx_thresh.sv"
    `include "seq_RCOV010_axi_bresp.sv"
    `include "seq_RCOV011_axi_rresp.sv"
    `include "seq_RCOV012_axi_write_order.sv"
    `include "seq_RCOV013_baud_tuning_write_while_enabled.sv"
    `include "seq_RCOV014_scratch.sv"
    `include "seq_RCOV015_reset_values.sv"
    `include "seq_RCOV016_uart_en_control.sv"
    `include "seq_RCOV017_frame_structural.sv"
    `include "seq_RCOV018_readonly_ignore.sv"
    `include "seq_RCOV019_int_thresh_frame.sv"
    `include "buffered_axi_lite_uart_agent.sv"
    `include "buffered_axi_lite_uart_env.sv"
    `include "buffered_axi_lite_uart_test.sv"
    `include "buffered_axi_lite_uart_regression_test.sv"
endpackage
