// ==============================================================
// File       : buffered_axi_lite_uart_driver.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : buffered_axi_lite_uart UVM driver — drives axi4_lite_seq_item
//              onto virtual balu_axi_if. Template parameter is the within-package
//              axi4_lite_seq_item to avoid xelab 2025.1 cross-pkg crash.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
//   2026-04-19  pssgen  RAL Session 3: within-package template parameter
// ==============================================================
class buffered_axi_lite_uart_driver extends uvm_driver #(axi4_lite_seq_item);
    `uvm_component_utils(buffered_axi_lite_uart_driver)

    virtual balu_axi_if vif;

    function new(string name, uvm_component parent);
        super.new(name, parent);
    endfunction

    function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        if (!uvm_config_db #(virtual balu_axi_if)::get(
                this, "", "vif", vif))
            `uvm_fatal("NO_VIF",
                "buffered_axi_lite_uart_driver: vif not found in config_db")
    endfunction

    task run_phase(uvm_phase phase);
        axi4_lite_seq_item req;
        vif.AWVALID <= 1'b0;
        vif.AWADDR  <= '0;
        vif.AWPROT  <= '0;
        vif.WVALID  <= 1'b0;
        vif.WDATA   <= '0;
        vif.WSTRB   <= '0;
        vif.BREADY  <= 1'b0;
        vif.ARVALID <= 1'b0;
        vif.ARADDR  <= '0;
        vif.ARPROT  <= '0;
        vif.RREADY  <= 1'b0;
        @(posedge vif.ACLK iff vif.ARESETn === 1'b1);
        forever begin
            seq_item_port.get_next_item(req);
            if (req.kind === axi4_lite_seq_item::WRITE)
                drive_write(req);
            else
                drive_read(req);
            seq_item_port.item_done();
        end
    endtask

    task drive_write(axi4_lite_seq_item req);
        logic aw_done, w_done;
        aw_done = 1'b0;
        w_done  = 1'b0;

        @(posedge vif.ACLK);
        vif.AWVALID <= 1'b1;
        vif.AWADDR  <= req.addr;
        vif.AWPROT  <= 3'b000;
        vif.WVALID  <= 1'b1;
        vif.WDATA   <= req.data;
        vif.WSTRB   <= req.strb;

        while (!aw_done || !w_done) begin
            @(posedge vif.ACLK);
            if (vif.AWREADY && !aw_done) begin
                vif.AWVALID <= 1'b0;
                vif.AWADDR  <= '0;
                aw_done = 1'b1;
            end
            if (vif.WREADY && !w_done) begin
                vif.WVALID <= 1'b0;
                vif.WDATA  <= '0;
                vif.WSTRB  <= '0;
                w_done = 1'b1;
            end
        end

        vif.BREADY <= 1'b1;
        @(posedge vif.ACLK iff vif.BVALID === 1'b1);
        req.resp = vif.BRESP;
        @(posedge vif.ACLK);
        vif.BREADY <= 1'b0;
    endtask

    task drive_read(axi4_lite_seq_item req);
        @(posedge vif.ACLK);
        vif.ARVALID <= 1'b1;
        vif.ARADDR  <= req.addr;
        vif.ARPROT  <= 3'b000;
        @(posedge vif.ACLK iff vif.ARREADY === 1'b1);
        vif.ARVALID <= 1'b0;
        vif.ARADDR  <= '0;

        vif.RREADY <= 1'b1;
        @(posedge vif.ACLK iff vif.RVALID === 1'b1);
        req.data = vif.RDATA;
        req.resp = vif.RRESP;
        @(posedge vif.ACLK);
        vif.RREADY <= 1'b0;
    endtask

endclass
