// ==============================================================
// File       : seq_RCOV014_scratch.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-014: SCRATCH — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 2 VSL step(s)) : Generated from Stimulus_VSL — COV-014
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-REG-044, UART-REG-045, UART-REG-046, UART-VER-003
// Stimulus strategy  : Write walking-ones ('h00000001 through 'h80000000), all-ones ('hFFFFFFFF), and all-zeros ('h00000000) to SCRATCH; read back and verify each value.
// Boundary values    : 'h00000001..'h80000000 (walking ones), 'h000000FF, 'hFFFFFFFF (all-ones), 'h00000000 (all-zeros)

class seq_RCOV014_scratch extends buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(seq_RCOV014_scratch)

    function new(string name = "seq_RCOV014_scratch");
        super.new(name);
    endfunction

    virtual task body();
        uvm_reg_data_t rdata;
        // Step 1: WRITE SCRATCH (0x24)
        axi_write(32'h00000024, 32'h00000001);
        // Step 2: READ SCRATCH (0x24)
        axi_read(32'h00000024, rdata);
        `uvm_info(get_name(), $sformatf("SCRATCH = 0x%0h, expect 0x%0h", rdata, 'h00000001), UVM_LOW)
    endtask : body

endclass