// ==============================================================
// File       : seq_RCOV004_fifo_status_rx_level.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-004: FIFO_STATUS.RX_LEVEL — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 5 VSL step(s)) : Generated from Stimulus_VSL — COV-004
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-FIFO-004, UART-FIFO-005, UART-FIFO-007, UART-FIFO-009, UART-REG-019, UART-REG-034
// Stimulus strategy  : RX FIFO occupancy driven to 0, RX_THRESH-1, RX_THRESH, RX_THRESH+1, and G_FIFO_DEPTH to verify status flags and overrun discard.
// Boundary values    : 0 (RX_EMPTY), RX_THRESH-1, RX_THRESH, RX_THRESH+1 (interrupt fires), G_FIFO_DEPTH (full/overrun)

class seq_RCOV004_fifo_status_rx_level extends buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(seq_RCOV004_fifo_status_rx_level)

    function new(string name = "seq_RCOV004_fifo_status_rx_level");
        super.new(name);
    endfunction

    virtual task body();
        uvm_reg_data_t rdata;
        reset_dut();
        axi_write(32'h00000008, 32'h10100000); // re-init BAUD_TUNING after reset
        // CTRL (0x00): UART_EN(7)+TX_EN(6)+RX_EN(5)+LOOP_EN(4) = 0xF0
        axi_write(32'h00000000, 32'hF0);
        // TX_DATA (0x28)
        axi_write(32'h00000028, 32'hAA);
        // Poll STATUS (0x04): wait until RX_EMPTY(bit6) = 0; 1 byte at 115200 baud ≈ 8680 cycles
        axi_poll(32'h00000004, 32'h40, 32'h00, 3000);
        // Read FIFO_STATUS (0x10): RX_LEVEL in [7:0]
        axi_read(32'h00000010, rdata);
        `uvm_info(get_name(), $sformatf("FIFO_STATUS = 0x%0h (RX_LEVEL=%0d)", rdata, rdata[7:0]), UVM_LOW)
    endtask : body

endclass