// ==============================================================
// File       : seq_RCOV002_ctrl_parity.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-002: CTRL.PARITY — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 6 VSL step(s)) : Generated from Stimulus_VSL — COV-002
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-FF-005, UART-FF-006, UART-FF-007, UART-FF-008, UART-FF-009, UART-REG-009, UART-VER-009
// Stimulus strategy  : All four parity modes (00/01/10/11) exercised independently in LOOP_EN loopback; inject parity error bit for odd and even modes.
// Boundary values    : 2'b00 (none), 2'b01 (odd+error inject), 2'b10 (even+error inject), 2'b11 (mark)

class seq_RCOV002_ctrl_parity extends buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(seq_RCOV002_ctrl_parity)

    function new(string name = "seq_RCOV002_ctrl_parity");
        super.new(name);
    endfunction

    virtual task body();
        uvm_reg_data_t rdata;
        reset_dut();
        // CTRL (0x00): UART_EN(7)+TX_EN(6)+RX_EN(5)+LOOP_EN(4)+ODD_PARITY(3:2=01) = 0xF4
        axi_write(32'h00000000, 32'hF4);
        // TX_DATA (0x28)
        axi_write(32'h00000028, 32'h41);
        // Poll STATUS (0x04): wait until RX_EMPTY(bit6) = 0; 1 byte at 115200 baud ≈ 8680 cycles
        axi_poll(32'h00000004, 32'h40, 32'h00, 3000);
        // Read RX_DATA (0x2C)
        axi_read(32'h0000002C, rdata);
        `uvm_info(get_name(), $sformatf("RX_DATA = 0x%0h, expect 0x%0h", rdata, 'h41), UVM_LOW)
    endtask : body

endclass