// ==============================================================
// File       : seq_RCOV005_fifo_status_tx_level.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-005: FIFO_STATUS.TX_LEVEL — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 5 VSL step(s)) : Generated from Stimulus_VSL — COV-005
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-FIFO-002, UART-FIFO-003, UART-FIFO-006, UART-FIFO-008, UART-REG-016, UART-REG-017, UART-REG-033
// Stimulus strategy  : TX FIFO occupancy driven to 0, TX_THRESH-1, TX_THRESH, TX_THRESH+1, and G_FIFO_DEPTH to verify status flags and write-ignore behavior.
// Boundary values    : 0 (TX_EMPTY), TX_THRESH-1, TX_THRESH, TX_THRESH+1 (interrupt fires), G_FIFO_DEPTH (full)

class seq_RCOV005_fifo_status_tx_level extends buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(seq_RCOV005_fifo_status_tx_level)

    function new(string name = "seq_RCOV005_fifo_status_tx_level");
        super.new(name);
    endfunction

    virtual task body();
        uvm_reg_data_t rdata;
        // CTRL (0x00): UART_EN(7) only — TX_EN not set so TX FIFO does not drain
        axi_write(32'h00000000, 32'h80);
        // Write 3 bytes to TX_DATA (0x28); with TX_EN=0 they queue in TX FIFO
        axi_write(32'h00000028, 32'hAA);
        axi_write(32'h00000028, 32'h55);
        axi_write(32'h00000028, 32'hFF);
        // Read FIFO_STATUS (0x10): TX_LEVEL in [15:8]
        axi_read(32'h00000010, rdata);
        `uvm_info(get_name(), $sformatf("FIFO_STATUS = 0x%0h (TX_LEVEL=%0d)", rdata, rdata[15:8]), UVM_LOW)
    endtask : body

endclass