// ==============================================================
// File       : seq_RCOV007_int_status_each_bit_independently.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-007: INT_STATUS each_bit_independently — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 5 VSL step(s)) : Generated from Stimulus_VSL — COV-007
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-INT-001, UART-INT-002, UART-INT-003, UART-INT-004, UART-INT-005, UART-INT-006, UART-INT-007, UART-INT-008, UART-REG-037, UART-REG-039, UART-REG-040, UART-VER-004
// Stimulus strategy  : Each of 8 interrupt sources set and cleared independently via directed stimulus; verify IRQ asserts and deasserts correctly for each bit.
// Boundary values    : Each of 8 bits: TIMEOUT, TX_THRESH, RX_THRESH, TX_EMPTY, RX_FULL, PARITY_ERR, FRAME_ERR, OVERRUN — set and W1C cleared independently

class seq_RCOV007_int_status_each_bit_independently extends buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(seq_RCOV007_int_status_each_bit_independently)

    function new(string name = "seq_RCOV007_int_status_each_bit_independently");
        super.new(name);
    endfunction

    virtual task body();
        uvm_reg_data_t rdata;
        reset_dut();
        // Step 1: INT_ENABLE (0x18): IE_TX_EMPTY(bit4=0x10)
        axi_write(32'h00000018, 32'h10);
        // Step 2: CTRL (0x00): UART_EN(7)+TX_EN(6) = 0xC0; TX FIFO empty on reset fires TX_EMPTY
        axi_write(32'h00000000, 32'hC0);
        // Step 3: Poll INT_STATUS (0x1C): wait for IS_TX_EMPTY(bit4=0x10)
        axi_poll(32'h0000001C, 32'h10, 32'h10, 100);
        // Step 4: INT_CLEAR (0x20): clear IS_TX_EMPTY bit
        axi_write(32'h00000020, 32'h10);
        // Step 5: Read INT_STATUS (0x1C): verify cleared
        axi_read(32'h0000001C, rdata);
        `uvm_info(get_name(), $sformatf("INT_STATUS = 0x%0h, expect 0x%0h", rdata, 'h00), UVM_LOW)
    endtask : body

endclass