// ==============================================================
// File       : seq_RCOV017_frame_structural.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-017: FRAME_STRUCTURAL — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 5 VSL step(s)) : Generated from Stimulus_VSL — COV-017
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-FF-001, UART-FIFO-001, UART-IF-001, UART-IF-002, UART-IF-003, UART-IF-004, UART-IF-012, UART-IF-013, UART-IF-014, UART-PAR-001, UART-PAR-002, UART-PAR-009, UART-REG-032, UART-REG-033, UART-REG-034
// Stimulus strategy  : Structural inspection: verify 8-bit data frames transmitted and received, AXI data width=32, address width sufficient, single-beat transactions only.
// Boundary values    : 8-bit frames; FIFO depth=G_FIFO_DEPTH; AXI data width=32; no burst transactions

class seq_RCOV017_frame_structural extends buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(seq_RCOV017_frame_structural)

    function new(string name = "seq_RCOV017_frame_structural");
        super.new(name);
    endfunction

    virtual task body();
        uvm_reg_data_t rdata;
        reset_dut();
        axi_write(32'h00000008, 32'h10000000); // re-init BAUD_TUNING after reset
        // CTRL (0x00): UART_EN(7)+TX_EN(6)+RX_EN(5)+LOOP_EN(4)+STOP_BITS(1) = 0xF2
        // Tests 2-stop-bit frame format in loopback
        axi_write(32'h00000000, 32'hF2);
        // Read CTRL back to verify frame config accepted
        axi_read(32'h00000000, rdata);
        `uvm_info(get_name(), $sformatf("CTRL = 0x%0h, expect 0x%0h", rdata, 'hF2), UVM_LOW)
        // TX byte via TX_DATA (0x28)
        axi_write(32'h00000028, 32'hA5);
        // Poll STATUS (0x04): wait until RX_EMPTY(bit6) = 0; 1 byte at 115200 baud ≈ 8680 cycles
        axi_poll(32'h00000004, 32'h40, 32'h00, 3000);
        // Read RX_DATA (0x2C)
        axi_read(32'h0000002C, rdata);
        `uvm_info(get_name(), $sformatf("RX_DATA = 0x%0h, expect 0x%0h", rdata, 'hA5), UVM_LOW)
    endtask : body

endclass