// ==============================================================
// File       : seq_RCOV001_baud_tuning.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-001: BAUD_TUNING — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 3 VSL step(s)) : Generated from Stimulus_VSL — COV-001
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-BR-001, UART-BR-002, UART-BR-003, UART-BR-005, UART-BR-006, UART-PAR-004, UART-PAR-005, UART-PAR-007, UART-REG-026, UART-REG-027
// Stimulus strategy  : NCO tuning word sweep at 12 values from minimum ('h00000001) to maximum ('hFFFFFFFF) including all standard baud rates.
// Boundary values    : 'h00000001 (min), standard baud rates 9600-921600, 3/4 Mbaud, 'hFFFFFFFF (max)

class seq_RCOV001_baud_tuning extends buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(seq_RCOV001_baud_tuning)

    function new(string name = "seq_RCOV001_baud_tuning");
        super.new(name);
    endfunction

    virtual task body();
        uvm_reg_data_t rdata;
        reset_dut();
        // Step 1: WRITE BAUD_TUNING (0x08)
        axi_write(32'h00000008, 32'h000010D6);
        // Step 2: WAIT
        repeat(256) @(posedge vif.ACLK);
        // Step 3: READ back BAUD_TUNING to confirm write accepted
        axi_read(32'h00000008, rdata);
        `uvm_info(get_name(), $sformatf("BAUD_TUNING = 0x%0h, expect 0x%0h", rdata, 'h000010D6), UVM_LOW)
    endtask : body

endclass