// ==============================================================
// File       : seq_RCOV013_baud_tuning_write_while_enabled.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-013: BAUD_TUNING_WRITE_WHILE_ENABLED — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 4 VSL step(s)) : Generated from Stimulus_VSL — COV-013
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-REG-028, UART-VER-007
// Stimulus strategy  : Assert UART_EN, write a new value to BAUD_TUNING, read back and verify original value unchanged; confirms silent-ignore while enabled.
// Boundary values    : UART_EN=1, write new value, readback must equal original value

class seq_RCOV013_baud_tuning_write_while_enabled extends buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(seq_RCOV013_baud_tuning_write_while_enabled)

    function new(string name = "seq_RCOV013_baud_tuning_write_while_enabled");
        super.new(name);
    endfunction

    virtual task body();
        uvm_reg_data_t rdata;
        reset_dut();
        // Step 1: WRITE BAUD_TUNING (0x08) before enabling
        axi_write(32'h00000008, 32'h000010D6);
        // Step 2: CTRL (0x00): set UART_EN(bit7=0x80) — blocks further BAUD_TUNING writes
        axi_write(32'h00000000, 32'h80);
        // Step 3: Attempt BAUD_TUNING write while UART_EN=1 — RTL silently ignores this
        axi_write(32'h00000008, 32'h00000001);
        // Step 4: Read BAUD_TUNING back — expect original value 0x000010D6 unchanged
        axi_read(32'h00000008, rdata);
    endtask : body

endclass