// ==============================================================
// File       : seq_RCOV008_int_status_overrun_int_status_rx_full.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-008: INT_STATUS.OVERRUN && INT_STATUS.RX_FULL — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 6 VSL step(s)) : Generated from Stimulus_VSL — COV-008
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-FIFO-007, UART-INT-005, UART-INT-006, UART-REG-018, UART-REG-024, UART-VER-005, UART-VER-010
// Stimulus strategy  : Fill RX FIFO to capacity then transmit additional byte to force overrun; verify overrun byte discarded and FIFO content unchanged.
// Boundary values    : RX FIFO at exactly G_FIFO_DEPTH, then one additional received byte

class seq_RCOV008_int_status_overrun_int_status_rx_full extends buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(seq_RCOV008_int_status_overrun_int_status_rx_full)

    function new(string name = "seq_RCOV008_int_status_overrun_int_status_rx_full");
        super.new(name);
    endfunction

    virtual task body();
        uvm_reg_data_t rdata;
        reset_dut();
        axi_write(32'h00000008, 32'h000010D6); // re-init BAUD_TUNING after reset
        // Step 1: INT_ENABLE (0x18): IE_RX_FULL(bit3=0x08) + IE_OVERRUN(bit0=0x01)
        axi_write(32'h00000018, 32'h09);
        // Step 2: CTRL (0x00): UART_EN(7)+TX_EN(6)+RX_EN(5)+LOOP_EN(4) = 0xF0
        axi_write(32'h00000000, 32'hF0);
        // Step 3: Write 17 bytes via TX_DATA (0x28); 16 fill RX FIFO, 17th causes overrun
        repeat(17) axi_write(32'h00000028, 32'hFF);
        // Step 4: Poll STATUS (0x04): wait for RX_FULL(bit7=0x80); 16 bytes * 8680 cycles
        axi_poll(32'h00000004, 32'h80, 32'h80, 30000);
        // Step 5: Read INT_STATUS (0x1C) to observe flags
        axi_read(32'h0000001C, rdata);
        `uvm_info(get_name(), $sformatf("INT_STATUS = 0x%0h", rdata), UVM_LOW)
    endtask : body

endclass