// ==============================================================
// File       : seq_RCOV003_ctrl_stop_bits.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-003: CTRL.STOP_BITS — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 6 VSL step(s)) : Generated from Stimulus_VSL — COV-003
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-FF-002, UART-FF-003, UART-FF-004, UART-REG-010
// Stimulus strategy  : Both stop bit configurations (1 and 2 stop bits) exercised in LOOP_EN loopback with frame integrity check.
// Boundary values    : 1'b0 (1 stop bit), 1'b1 (2 stop bits)

class seq_RCOV003_ctrl_stop_bits extends axi4_lite_base_seq;

    `uvm_object_utils(seq_RCOV003_ctrl_stop_bits)

    function new(string name = "seq_RCOV003_ctrl_stop_bits");
        super.new(name);
    endfunction

    virtual task body();
        uvm_reg_data_t rdata;
        // Step 1: WRITE
        reg_write(reg_model.LOOPBACK, 0x01);
        // Step 2: WRITE
        reg_write(reg_model.FRAME, 0x08);
        // Step 3: WRITE
        reg_write(reg_model.CTRL, 0x03);
        // Step 4: WRITE
        reg_write(reg_model.TX_DATA, 0x55);
        // Step 5: POLL
        reg_poll(reg_model.STATUS, 0x02, 0x02, 1000);
        // Step 6: READ
        reg_read(reg_model.RX_DATA, rdata);
        `uvm_info(get_name(), $sformatf("Read 0x%0h, expect 0x%0h", rdata, 0x55), UVM_LOW)
    endtask : body

endclass