// ==============================================================
// File       : seq_RCOV011_axi_rresp.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-011: AXI_RRESP — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 4 VSL step(s)) : Generated from Stimulus_VSL — COV-011
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-IF-007, UART-IF-009, UART-REG-001
// Stimulus strategy  : AXI read from valid register offset (OKAY expected) and from undefined offset 'h30 (SLVERR expected); capture RRESP each time.
// Boundary values    : Valid offset RRESP=OKAY, undefined offset 'h30 RRESP=SLVERR

class seq_RCOV011_axi_rresp extends buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(seq_RCOV011_axi_rresp)

    function new(string name = "seq_RCOV011_axi_rresp");
        super.new(name);
    endfunction

    virtual task body();
        uvm_reg_data_t rdata;
        reset_dut();
        // Step 1: WRITE
        axi_write(32'h00000000, 'h03);
        // Step 2: READ
        axi_read(32'h00000000, rdata);
        `uvm_info(get_name(), $sformatf("Read 0x%0h, expect 0x%0h", rdata, 'h03), UVM_LOW)
        // Step 3: READ — use SCRATCH (undefined offsets not in RAL model; using last RW regs)
        axi_read(32'h0000002C, rdata);
        // Step 4: READ
        axi_read(32'h00000034, rdata);
    endtask : body

endclass