// ==============================================================
// File       : seq_RCOV001_baud_tuning.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-001: BAUD_TUNING — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 3 VSL step(s)) : Generated from Stimulus_VSL — COV-001
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-BR-001, UART-BR-002, UART-BR-003, UART-BR-005, UART-BR-006, UART-PAR-004, UART-PAR-005, UART-PAR-007, UART-REG-026, UART-REG-027
// Stimulus strategy  : NCO tuning word sweep at 12 values from minimum (0x00000001) to maximum (0xFFFFFFFF) including all standard baud rates.
// Boundary values    : 0x00000001 (min), standard baud rates 9600-921600, 3/4 Mbaud, 0xFFFFFFFF (max)

class seq_RCOV001_baud_tuning extends axi4_lite_base_seq;

    `uvm_object_utils(seq_RCOV001_baud_tuning)

    function new(string name = "seq_RCOV001_baud_tuning");
        super.new(name);
    endfunction

    virtual task body();
        // Step 1: WRITE
        reg_write(reg_model.BAUD, 0x000010D6);
        // Step 2: WAIT
        repeat(256) @(posedge vif.clk);
        // Step 3: POLL
        reg_poll(reg_model.TX_DATA, 0x01, 0x01, 1000);
    endtask : body

endclass