// ==============================================================
// File       : seq_RCOV019_int_thresh_frame.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-019: INT_THRESH_FRAME — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 6 VSL step(s)) : Generated from Stimulus_VSL — COV-019
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-INT-009, UART-INT-010, UART-INT-011, UART-INT-012, UART-INT-013, UART-TO-007, UART-REG-015, UART-REG-020, UART-REG-021, UART-REG-022, UART-REG-023, UART-REG-029, UART-REG-030, UART-REG-037, UART-REG-039, UART-REG-040, UART-REG-041, UART-REG-043, UART-REG-047, UART-REG-048, UART-REG-050, UART-REG-051
// Stimulus strategy  : Drive TX_THRESH and RX_THRESH interrupt conditions, inject FRAME_ERR via stop-bit corruption, enable TIMEOUT interrupt; verify each INT_STATUS bit controlled by INT_ENABLE gate.
// Boundary values    : TX FIFO below TX_THRESH; RX FIFO above RX_THRESH; stop-bit corruption for FRAME_ERR; TIMEOUT with INT_ENABLE gates

class seq_RCOV019_int_thresh_frame extends buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(seq_RCOV019_int_thresh_frame)

    function new(string name = "seq_RCOV019_int_thresh_frame");
        super.new(name);
    endfunction

    virtual task body();
        reset_dut();
        // Step 1: INT_ENABLE (0x18): IE_FRAME_ERR(bit1=0x02) + IE_PARITY_ERR(bit2=0x04)
        axi_write(32'h00000018, 32'h06);
        // Step 2: CTRL (0x00): UART_EN(7)+TX_EN(6)+RX_EN(5)+LOOP_EN(4)+ODD_PARITY(3:2=01)+STOP_BITS(1) = 0xF6
        // ODD_PARITY in loopback means parity check is consistent — frame error tests stop-bit
        axi_write(32'h00000000, 32'hF6);
        // Step 3: TX byte via TX_DATA (0x28)
        axi_write(32'h00000028, 32'hAB);
        // Step 4: Poll INT_STATUS (0x1C): wait for IS_FRAME_ERR(bit1=0x02)
        // Note: in perfect loopback FRAME_ERR may not fire; timeout here is expected
        axi_poll(32'h0000001C, 32'h02, 32'h02, 1000);
    endtask : body

endclass