// ==============================================================
// File       : seq_RCOV003_ctrl_stop_bits.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-003: CTRL.STOP_BITS — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 6 VSL step(s)) : Generated from Stimulus_VSL — COV-003
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-FF-002, UART-FF-003, UART-FF-004, UART-REG-010
// Stimulus strategy  : Both stop bit configurations (1 and 2 stop bits) exercised in LOOP_EN loopback with frame integrity check.
// Boundary values    : 1'b0 (1 stop bit), 1'b1 (2 stop bits)

class seq_RCOV003_ctrl_stop_bits extends buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(seq_RCOV003_ctrl_stop_bits)

    function new(string name = "seq_RCOV003_ctrl_stop_bits");
        super.new(name);
    endfunction

    virtual task body();
        uvm_reg_data_t rdata;
        reset_dut();
        axi_write(32'h00000008, 32'h00800000); // re-init BAUD_TUNING after reset
        // CTRL (0x00): UART_EN(7)+TX_EN(6)+RX_EN(5)+LOOP_EN(4)+STOP_BITS(1) = 0xF2
        axi_write(32'h00000000, 32'hF2);
        // TX_DATA (0x28)
        axi_write(32'h00000028, 32'h55);
        // Poll STATUS (0x04): wait until RX_EMPTY(bit6) = 0; 1 byte at 115200 baud ≈ 8680 cycles
        axi_poll(32'h00000004, 32'h40, 32'h00, 3000);
        // Read RX_DATA (0x2C)
        axi_read(32'h0000002C, rdata);
        `uvm_info(get_name(), $sformatf("RX_DATA = 0x%0h, expect 0x%0h", rdata, 'h55), UVM_LOW)
    endtask : body

endclass