// ==============================================================
// File       : seq_RCOV006_timeout_val.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-006: TIMEOUT_VAL — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 4 VSL step(s)) : Generated from Stimulus_VSL — COV-006
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-TO-001, UART-TO-002, UART-TO-003, UART-TO-004, UART-TO-005, UART-TO-006, UART-REG-035, UART-REG-036, UART-PAR-006, UART-VER-008
// Stimulus strategy  : TIMEOUT_VAL set to 'h0000, 'h0001, G_TIMEOUT_DEFAULT, 'hFFFE, and 'hFFFF; idle receiver until timeout fires for each non-zero value.
// Boundary values    : 'h0000 (disabled), 'h0001 (minimum active), G_TIMEOUT_DEFAULT (reset), 'hFFFE, 'hFFFF (maximum)

class seq_RCOV006_timeout_val extends buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(seq_RCOV006_timeout_val)

    function new(string name = "seq_RCOV006_timeout_val");
        super.new(name);
    endfunction

    virtual task body();
        uvm_reg_data_t rdata;
        // Step 1: WRITE TIMEOUT_VAL (0x14)
        axi_write(32'h00000014, 32'h0001);
        // Step 2: READ TIMEOUT_VAL
        axi_read(32'h00000014, rdata);
        `uvm_info(get_name(), $sformatf("TIMEOUT_VAL = 0x%0h, expect 0x%0h", rdata, 'h0001), UVM_LOW)
        // Step 3: WRITE TIMEOUT_VAL
        axi_write(32'h00000014, 32'hFFFF);
        // Step 4: READ TIMEOUT_VAL
        axi_read(32'h00000014, rdata);
        `uvm_info(get_name(), $sformatf("TIMEOUT_VAL = 0x%0h, expect 0x%0h", rdata, 'hFFFF), UVM_LOW)
    endtask : body

endclass