// ==============================================================
// File       : seq_RCOV014_scratch.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-014: SCRATCH — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 2 VSL step(s)) : Generated from Stimulus_VSL — COV-014
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-REG-044, UART-REG-045, UART-REG-046, UART-VER-003
// Stimulus strategy  : Write walking-ones (0x00000001 through 0x80000000), all-ones (0xFFFFFFFF), and all-zeros (0x00000000) to SCRATCH; read back and verify each value.
// Boundary values    : 0x00000001..0x80000000 (walking ones), 0x000000FF, 0xFFFFFFFF (all-ones), 0x00000000 (all-zeros)

class seq_RCOV014_scratch extends axi4_lite_base_seq;

    `uvm_object_utils(seq_RCOV014_scratch)

    function new(string name = "seq_RCOV014_scratch");
        super.new(name);
    endfunction

    virtual task body();
        uvm_reg_data_t rdata;
        // Step 1: WRITE
        reg_write(reg_model.SCRATCH, 0x00000001);
        // Step 2: READ
        reg_read(reg_model.SCRATCH, rdata);
        `uvm_info(get_name(), $sformatf("Read 0x%0h, expect 0x%0h", rdata, 0x00000001), UVM_LOW)
    endtask : body

endclass