// ==============================================================
// File       : seq_RCOV018_readonly_ignore.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-018: READONLY_IGNORE — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 6 VSL step(s)) : Generated from Stimulus_VSL — COV-018
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-IF-010, UART-IF-011, UART-REG-002, UART-REG-003, UART-REG-011, UART-REG-012, UART-REG-025, UART-REG-038, UART-REG-042, UART-REG-049, UART-REG-052
// Stimulus strategy  : Write to each read-only register (STATUS, FIFO_STATUS, INT_STATUS, INT_CLEAR, TX_DATA reads, RX_DATA writes); read back and verify state unchanged.
// Boundary values    : Write all-ones to each RO register; compare pre- and post-write readback for each

class seq_RCOV018_readonly_ignore extends buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(seq_RCOV018_readonly_ignore)

    function new(string name = "seq_RCOV018_readonly_ignore");
        super.new(name);
    endfunction

    virtual task body();
        uvm_reg_data_t rdata;
        // Step 1: Read STATUS (0x04, RO)
        axi_read(32'h00000004, rdata);
        // Step 2: Write to STATUS (0x04, RO) — RTL returns SLVERR, state unchanged
        axi_write(32'h00000004, 32'hFF);
        // Step 3: Read STATUS again — value unchanged
        axi_read(32'h00000004, rdata);
        // Step 4: Read FIFO_STATUS (0x10, RO)
        axi_read(32'h00000010, rdata);
        // Step 5: Write to FIFO_STATUS (0x10, RO) — RTL returns SLVERR, state unchanged
        axi_write(32'h00000010, 32'hFF);
        // Step 6: Read FIFO_STATUS again — value unchanged
        axi_read(32'h00000010, rdata);
    endtask : body

endclass