// ==============================================================
// File       : seq_RCOV009_int_status_timeout_int_status_rx_thresh.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-009: INT_STATUS.TIMEOUT && INT_STATUS.RX_THRESH — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 6 VSL step(s)) : Generated from Stimulus_VSL — COV-009
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-TO-005, UART-INT-002, UART-INT-008, UART-REG-014
// Stimulus strategy  : Set TIMEOUT_VAL non-zero, fill RX FIFO above RX_THRESH, then idle until timeout fires; verify both INT_STATUS.TIMEOUT and INT_STATUS.RX_THRESH set simultaneously.
// Boundary values    : RX FIFO > RX_THRESH (threshold set), then idle until timeout fires while threshold remains set

class seq_RCOV009_int_status_timeout_int_status_rx_thresh extends buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(seq_RCOV009_int_status_timeout_int_status_rx_thresh)

    function new(string name = "seq_RCOV009_int_status_timeout_int_status_rx_thresh");
        super.new(name);
    endfunction

    virtual task body();
        reset_dut();
        axi_write(32'h00000008, 32'h10000000); // re-init BAUD_TUNING after reset
        // Step 1: TIMEOUT_VAL (0x14): set non-zero to enable timeout
        axi_write(32'h00000014, 32'h0010);
        // Step 2: FIFO_CTRL (0x0C): set RX_THRESH=1 so 1 received byte fires IS_RX_THRESH
        axi_write(32'h0000000C, 32'h0801);
        // Step 3: INT_ENABLE (0x18): IE_TIMEOUT(bit7=0x80) + IE_RX_THRESH(bit5=0x20)
        axi_write(32'h00000018, 32'hA0);
        // Step 4: CTRL (0x00): UART_EN(7)+TX_EN(6)+RX_EN(5)+LOOP_EN(4) = 0xF0
        axi_write(32'h00000000, 32'hF0);
        // Step 5: Write byte via TX_DATA (0x28) — loopback puts it in RX FIFO above thresh
        axi_write(32'h00000028, 32'hAB);
        // Step 6: Poll INT_STATUS (0x1C): wait for IS_RX_THRESH(bit5=0x20); 1 byte ≈ 8680 cycles
        axi_poll(32'h0000001C, 32'h20, 32'h20, 3000);
    endtask : body

endclass