// ==============================================================
// File       : seq_RCOV015_reset_values.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-015: RESET_VALUES — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 5 VSL step(s)) : Generated from Stimulus_VSL — COV-015
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-RST-001, UART-RST-002, UART-RST-003, UART-RST-004, UART-RST-005, UART-RST-006, UART-REG-004, UART-REG-013, UART-REG-031, UART-REG-036, UART-REG-046, UART-PAR-007, UART-PAR-008, UART-VER-002
// Stimulus strategy  : Assert then deassert reset; read all 12 registers and compare each field to the reset value specified in Table 8-x.
// Boundary values    : 12 register reset values per spec Table 8-x

class seq_RCOV015_reset_values extends axi4_lite_base_seq;

    `uvm_object_utils(seq_RCOV015_reset_values)

    function new(string name = "seq_RCOV015_reset_values");
        super.new(name);
    endfunction

    virtual task body();
        uvm_reg_data_t rdata;
        // Step 1: WRITE
        reg_write(reg_model.CTRL, 0x80);
        // Step 2: WAIT
        repeat(10) @(posedge vif.clk);
        // Step 3: READ
        reg_read(reg_model.CTRL, rdata);
        // Step 4: READ
        reg_read(reg_model.STATUS, rdata);
        `uvm_info(get_name(), $sformatf("Read 0x%0h, expect 0x%0h", rdata, 0x01), UVM_LOW)
        // Step 5: READ
        reg_read(reg_model.BAUD, rdata);
    endtask : body

endclass