// ==============================================================
// File       : seq_RCOV010_axi_bresp.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-010: AXI_BRESP — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (PHASE_1 — 2 VSL step(s)) : Generated from Stimulus_VSL — COV-010
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : phase_1_generated
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-IF-006, UART-IF-008, UART-REG-001
// Stimulus strategy  : AXI write to valid register offset (OKAY expected) and to undefined offset 'h30 (SLVERR expected); capture BRESP each time.
// Boundary values    : Valid offset BRESP=OKAY, undefined offset 'h30 BRESP=SLVERR

class seq_RCOV010_axi_bresp extends buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(seq_RCOV010_axi_bresp)

    function new(string name = "seq_RCOV010_axi_bresp");
        super.new(name);
    endfunction

    virtual task body();
        uvm_reg_data_t rdata;
        // Step 1: WRITE
        axi_write(32'h00000000, 'h00000001);
        // Step 2: READ
        axi_read(32'h0000000C, rdata);
        `uvm_info(get_name(), $sformatf("Read 0x%0h, expect 0x%0h", rdata, 'h00), UVM_LOW)
    endtask : body

endclass