// ==============================================================
// File       : seq_RCOV012_axi_write_order.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : COV sequence stub for COV-012: AXI_WRITE_ORDER — implement per VPR Stimulus_Strategy.
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   body (SEQ_PENDING) : Stub — see VPR COV-012 for implementation guidance
//
// Dependencies:
//   buffered_axi_lite_uart_base_seq
//
// Portability    : Simulator-independent
// Impl. status   : stub
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
// Linked requirements: UART-IF-005, UART-VER-006
// Stimulus strategy  : Issue AXI write with AWVALID first then WVALID, then repeat with WVALID first then AWVALID; verify correct response in both orderings.
// Boundary values    : AWVALID_FIRST ordering, WVALID_FIRST ordering

class seq_RCOV012_axi_write_order extends buffered_axi_lite_uart_base_seq;

    `uvm_object_utils(seq_RCOV012_axi_write_order)

    function new(string name = "seq_RCOV012_axi_write_order");
        super.new(name);
    endfunction

    virtual task body();
        reset_dut();
        `uvm_info("SEQ_PENDING",
            "seq_RCOV012_axi_write_order: body not yet implemented — see VPR COV-012",
            UVM_MEDIUM)
    endtask

endclass