// ==============================================================
// File       : tb_top.sv
// Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
// Copyright  : Copyright (c) 2026 BelTech Systems LLC
// License    : MIT License — see LICENSE for details
// ==============================================================
// Brief      : tb_top — top-level testbench module; DUT instantiation, clock/reset, UVM run_test().
// Document   : BelTech-STD-003 Rev 1
// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2
//
// Functional blocks:
//   DUT instantiation  : AXI-Lite ports connected via balu_axi_if
//   Clock/reset        : 100 MHz clock; synchronous active-low reset (20 cycles)
//   UVM config_db      : Virtual balu_axi_if registration
//
// Dependencies:
//   uvm_pkg
//   buffered_axi_lite_uart_pkg
//   balu_axi_if
//
// Portability    : Vivado/Questa/Icarus
// Impl. status   : generated-ral
//
// History:
//   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
// ==============================================================
`timescale 1ns/1ps
module tb_top;
    import uvm_pkg::*;
    import buffered_axi_lite_uart_pkg::*;
    `include "uvm_macros.svh"

    // Free-running 100 MHz clock (10 ns period)
    logic clk;
    logic rst_n;
    initial clk = 1'b0;
    always #5 clk = ~clk;

    // UART loopback — connect uart_tx directly to uart_rx for Phase 1 testing
    logic uart_loopback;
    logic irq_unused;

    // DUT reset: hardware reset AND sequence-driven reset (for inter-sequence cleanup)
    logic dut_rst_n;
    assign dut_rst_n = rst_n & axi_if.ARESETn_seq;

    // AXI4-Lite interface from sim/lib
    balu_axi_if axi_if (
        .ACLK   (clk),
        .ARESETn(rst_n)
    );

    // DUT instantiation — BALU RTL AXI-Lite slave port names
    buffered_axi_lite_uart dut (
        .axi_aclk   (clk),
        .axi_aresetn(dut_rst_n),
        .s_axi_awaddr (axi_if.AWADDR[7:0]),
        .s_axi_awprot (3'b000),
        .s_axi_awvalid(axi_if.AWVALID),
        .s_axi_awready(axi_if.AWREADY),
        .s_axi_wdata  (axi_if.WDATA),
        .s_axi_wstrb  (axi_if.WSTRB),
        .s_axi_wvalid (axi_if.WVALID),
        .s_axi_wready (axi_if.WREADY),
        .s_axi_bresp  (axi_if.BRESP),
        .s_axi_bvalid (axi_if.BVALID),
        .s_axi_bready (axi_if.BREADY),
        .s_axi_araddr (axi_if.ARADDR[7:0]),
        .s_axi_arprot (3'b000),
        .s_axi_arvalid(axi_if.ARVALID),
        .s_axi_arready(axi_if.ARREADY),
        .s_axi_rdata  (axi_if.RDATA),
        .s_axi_rresp  (axi_if.RRESP),
        .s_axi_rvalid (axi_if.RVALID),
        .s_axi_rready (axi_if.RREADY),
        .uart_tx      (uart_loopback),
        .uart_rx      (uart_loopback),
        .irq          (irq_unused)
    );

    // Clock/reset generation
    initial begin
        rst_n = 1'b0;
        repeat (20) @(posedge clk);
        rst_n = 1'b1;
    end

    // Register virtual interface and launch UVM test
    initial begin
        uvm_config_db #(virtual balu_axi_if)::set(
            null, "uvm_test_top.*", "vif", axi_if);
        run_test();
    end

    // Waveform dump
    initial begin
        $dumpfile("tb_top.vcd");
        $dumpvars(0, tb_top);
    end

endmodule