# ==============================================================
# File       : build.tcl
# Project    : pssgen — AI-Driven PSS + UVM + C Testbench Generator
# Copyright  : Copyright (c) 2026 BelTech Systems LLC
# License    : MIT License — see LICENSE for details
# ==============================================================
# Brief      : buffered_axi_lite_uart Vivado/XSIM build and run script — three-file compile model per STD-003.
# Document   : BelTech-STD-003 Rev 1
# Tool       : Vivado 2024.x / XSIM
#
# Usage:
#   vivado -mode tcl -source build.tcl
#
# Impl. status   : generated
#
# History:
#   2026-04-18  pssgen  Generated by scaffold_gen.generate_uvm_tb()
# ==============================================================
set DESIGN   buffered_axi_lite_uart
set SNAPSHOT ${DESIGN}_snapshot

set SCRIPT_DIR [file dirname [file normalize [info script]]]
set TB_DIR     [file join $SCRIPT_DIR ../..]
set DUT_DIR    [file join $SCRIPT_DIR ../../..]

proc run_cmd {cmd} {
    if {[catch {exec {*}$cmd >@stdout 2>@stderr} msg]} {
        puts "ERROR: Command failed:"
        puts "  $cmd"
        puts $msg
        exit 1
    }
}

puts "--- Compiling DUT ---"
run_cmd [list xvhdl --2008 --work work \
    [file join $DUT_DIR vhdl/${DESIGN}.vhd]]

puts "--- Compiling UVM TB ---"
run_cmd [list xvlog --sv --uvm_version 1.2 -L uvm --work work \
    --include $TB_DIR \
    [file join $TB_DIR ${DESIGN}_if.sv] \
    [file join $TB_DIR ${DESIGN}_pkg.sv] \
    [file join $TB_DIR tb_top.sv]]

puts "--- Elaborating ---"
run_cmd [list xelab -L uvm \
    work.tb_top \
    -s $SNAPSHOT \
    -timescale 1ns/1ps \
    -debug typical]

puts "--- Simulating ---"
run_cmd [list xsim $SNAPSHOT \
    -testplusarg UVM_TESTNAME=${DESIGN}_smoke_test \
    -runall \
    -log xsim.log]

puts "Simulation complete. Log: xsim.log"
