# ===========================================================
# FILE:         agents/closure_gen.py
# PROJECT:      pssgen — AI-Driven PSS + UVM + C Testbench Generator
# COPYRIGHT:    Copyright (c) 2026 BelTech Systems LLC
# LICENSE:      MIT License — see LICENSE file for details
# ===========================================================
#
# DESCRIPTION:
#   Generates simulator-specific closure shell scripts that run the
#   simulation, copy coverage output to a known location, and invoke
#   pssgen for the next coverage-guided pass. Supports four targets:
#   vivado, questa, icarus, and none. Always produces both .sh and .bat
#   variants so the script can be used on Linux/macOS or Windows.
#
# LAYER:        3 — agents
# PHASE:        v3c-b
#
# FUNCTIONS:
#   generate_closure_script(ir, sim_target, pass_number, gap_report, out_dir)
#     Write run_closure_pass_N.sh (and .bat) for the given simulator target.
#
# DEPENDENCIES:
#   Standard library:  os
#   Internal:          ir, agents.gap_agent
#
# HISTORY:
#   v3c-b  2026-03-29  SB  Initial implementation; four simulator targets
#
# ===========================================================
"""agents/closure_gen.py — Coverage closure script generator.

Phase: v3c-b
Layer: 3 (agents)

Generates run_closure_pass_N.sh and .bat scripts for each simulator
target. Scripts run simulation, copy coverage output, and invoke pssgen
for the next guided pass.
"""
from __future__ import annotations

import os

from ir import IR
from agents.gap_agent import GapReport


# Supported closure targets. The main emitter dispatch handles vivado,
# questa, and generic — closure adds icarus and none as script-only targets.
_SUPPORTED_TARGETS = frozenset({"vivado", "questa", "icarus", "none"})


def generate_closure_script(
    ir: IR,
    sim_target: str,
    pass_number: int,
    gap_report: GapReport,
    out_dir: str,
) -> str:
    """Generate a closure shell script for the next simulation pass.

    Creates a simulator-specific script that runs the simulation, copies
    coverage output to a known location, and invokes pssgen with updated
    coverage data for the next guided pass. Both ``.sh`` (Linux/macOS) and
    ``.bat`` (Windows) variants are written to ``out_dir``.

    Script naming convention: ``run_closure_pass_<N>.sh``

    Args:
        ir: Populated design IR (provides design name and output directory).
        sim_target: Simulator target — one of vivado, questa, icarus, none.
        pass_number: Current closure pass number (1-based).
        gap_report: Current gap report, used to annotate remaining gap counts.
        out_dir: Directory to write the script files.

    Returns:
        Absolute path to the written ``.sh`` script file.

    Raises:
        NotImplementedError: If ``sim_target`` is not one of the four
            supported targets.
    """
    if sim_target not in _SUPPORTED_TARGETS:
        raise NotImplementedError(
            f"Closure script generation not supported for sim_target "
            f"'{sim_target}'. Supported: {sorted(_SUPPORTED_TARGETS)}"
        )

    os.makedirs(out_dir, exist_ok=True)
    abs_out = os.path.abspath(out_dir)
    design = ir.design_name
    n_errors = len(gap_report.errors)
    n_warnings = len(gap_report.warnings)

    sh_name = f"run_closure_pass_{pass_number}.sh"
    bat_name = f"run_closure_pass_{pass_number}.bat"
    sh_path = os.path.join(abs_out, sh_name)
    bat_path = os.path.join(abs_out, bat_name)

    sh_content = _build_sh_script(
        sim_target=sim_target,
        pass_number=pass_number,
        design=design,
        out_dir=abs_out,
        n_errors=n_errors,
        n_warnings=n_warnings,
    )
    bat_content = _build_bat_script(
        sim_target=sim_target,
        pass_number=pass_number,
        design=design,
        out_dir=abs_out,
        n_errors=n_errors,
        n_warnings=n_warnings,
    )

    # Write .sh with Unix line endings; .bat with Windows line endings.
    with open(sh_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(sh_content)
    with open(bat_path, "w", encoding="utf-8", newline="\r\n") as fh:
        fh.write(bat_content)

    return sh_path


# ---------------------------------------------------------------------------
# Internal script builders
# ---------------------------------------------------------------------------

def _sh_header(pass_number: int, n_errors: int, n_warnings: int) -> str:
    """Return the standard bash script header block."""
    return (
        "#!/usr/bin/env bash\n"
        f"# pssgen closure script — pass {pass_number}\n"
        "# Generated by pssgen v3c-b — BelTech Systems LLC\n"
        f"# Gaps remaining: {n_errors} error(s), {n_warnings} warning(s)\n"
        "# Run this script, then run pssgen again to update\n"
        "# the gap report with new coverage data.\n"
        "\n"
        "set -e\n"
        "\n"
    )


def _build_sh_script(
    sim_target: str,
    pass_number: int,
    design: str,
    out_dir: str,
    n_errors: int,
    n_warnings: int,
) -> str:
    """Build the .sh script body for the given simulator target."""
    header = _sh_header(pass_number, n_errors, n_warnings)

    if sim_target == "vivado":
        body = (
            f'echo "Running Vivado simulation — pass {pass_number}..."\n'
            f"cd {out_dir}\n"
            "vivado -mode batch -source build.tcl -notrace\n"
            "\n"
            'echo "Copying coverage output..."\n'
            f"cp xsim.dir/{design}_test/coverage.xml \\\n"
            f"   {out_dir}/{design}_coverage_pass{pass_number}.xml\n"
            "\n"
            'echo "Running pssgen coverage analysis..."\n'
            "pssgen \\\n"
            f"  --coverage-db {out_dir}/{design}_coverage_pass{pass_number}.xml \\\n"
            "  --coverage-loop 1\n"
            "\n"
            f'echo "Done. Check {design}_gap_report.txt for results."\n'
        )

    elif sim_target == "questa":
        body = (
            # OI-12: Questa UCDB binary format reading — deferred.
            "# OI-12: Questa UCDB binary format reading — deferred.\n"
            "# Requires vcover command or pyucis library.\n"
            "# Current output assumes Vivado-compatible XML path.\n"
            "\n"
            f'echo "Running Questa simulation — pass {pass_number}..."\n'
            f"cd {out_dir}\n"
            "make simulate\n"
            "\n"
            'echo "Copying coverage output..."\n'
            "# Adjust questa_cov_db path to match your Questa installation.\n"
            f"cp questa_cov_db/{design}_cov.xml \\\n"
            f"   {out_dir}/{design}_coverage_pass{pass_number}.xml\n"
            "\n"
            'echo "Running pssgen coverage analysis..."\n'
            "pssgen \\\n"
            f"  --coverage-db {out_dir}/{design}_coverage_pass{pass_number}.xml \\\n"
            "  --coverage-loop 1\n"
            "\n"
            f'echo "Done. Check {design}_gap_report.txt for results."\n'
        )

    elif sim_target == "icarus":
        body = (
            "# Note: UVM requires the UVM base library compiled separately.\n"
            "# See README for iverilog UVM setup.\n"
            "\n"
            f'echo "Running Icarus Verilog simulation — pass {pass_number}..."\n'
            f"cd {out_dir}\n"
            f"iverilog -g2012 -o {design}_sim *.sv\n"
            f"vvp {design}_sim -lxt2\n"
            "\n"
            "# Icarus does not natively output Vivado XML format.\n"
            "# Coverage data must be extracted manually or via a\n"
            "# VCD-to-coverage converter.\n"
            "# pssgen will read pre-existing coverage XML if provided:\n"
            "#\n"
            "# pssgen --coverage-db <path_to_coverage.xml> --coverage-loop 1\n"
            "\n"
            f'echo "Simulation done. Provide coverage XML to pssgen for gap update."\n'
        )

    else:  # none
        body = (
            "# No simulator configured. Run your simulation manually,\n"
            "# then re-run pssgen with the coverage XML output:\n"
            "#\n"
            "# pssgen --coverage-db <path_to_coverage.xml> \\\n"
            "#        --coverage-loop 1\n"
            '\necho "No simulator configured."\n'
            'echo "Run your simulation and provide coverage XML."\n'
        )

    return header + body


def _build_bat_script(
    sim_target: str,
    pass_number: int,
    design: str,
    out_dir: str,
    n_errors: int,
    n_warnings: int,
) -> str:
    """Build the Windows .bat script equivalent."""
    lines: list[str] = [
        "@echo off",
        f"REM pssgen closure script — pass {pass_number}",
        "REM Generated by pssgen v3c-b — BelTech Systems LLC",
        f"REM Gaps remaining: {n_errors} error(s), {n_warnings} warning(s)",
        "",
    ]

    if sim_target == "vivado":
        lines += [
            f'echo Running Vivado simulation — pass {pass_number}...',
            f'cd /d "{out_dir}"',
            "vivado -mode batch -source build.tcl -notrace",
            "",
            "echo Copying coverage output...",
            f'copy "xsim.dir\\{design}_test\\coverage.xml" '
            f'"{out_dir}\\{design}_coverage_pass{pass_number}.xml"',
            "",
            "echo Running pssgen coverage analysis...",
            "pssgen ^",
            f'  --coverage-db "{out_dir}\\{design}_coverage_pass{pass_number}.xml" ^',
            "  --coverage-loop 1",
            "",
            f"echo Done. Check {design}_gap_report.txt for results.",
        ]
    elif sim_target == "questa":
        lines += [
            "REM OI-12: Questa UCDB binary format reading — deferred.",
            f'echo Running Questa simulation — pass {pass_number}...',
            f'cd /d "{out_dir}"',
            "make simulate",
            f'copy "questa_cov_db\\{design}_cov.xml" '
            f'"{out_dir}\\{design}_coverage_pass{pass_number}.xml"',
            "pssgen ^",
            f'  --coverage-db "{out_dir}\\{design}_coverage_pass{pass_number}.xml" ^',
            "  --coverage-loop 1",
        ]
    elif sim_target == "icarus":
        lines += [
            "REM Note: UVM requires the UVM base library compiled separately.",
            f'echo Running Icarus Verilog simulation — pass {pass_number}...',
            f'cd /d "{out_dir}"',
            f"iverilog -g2012 -o {design}_sim.exe *.sv",
            f"vvp {design}_sim.exe",
            "REM Provide coverage XML manually:",
            "REM pssgen --coverage-db <path_to_coverage.xml> --coverage-loop 1",
        ]
    else:  # none
        lines += [
            "REM No simulator configured.",
            "echo No simulator configured.",
            "echo Run your simulation and provide coverage XML.",
        ]

    return "\r\n".join(lines) + "\r\n"
