import json
from datetime import datetime, timezone


def generate_coverage_report(
    coverage_assessment_path: str,
    code_coverage_path: str,
    functional_coverage_path: str,
    assertion_coverage_path: str,
    output_path: str
) -> str:
    with open(coverage_assessment_path) as f:
        ca = json.load(f)
    with open(code_coverage_path) as f:
        cc = json.load(f)
    with open(functional_coverage_path) as f:
        fc = json.load(f)
    with open(assertion_coverage_path) as f:
        ac = json.load(f)

    m = ca.get("coverage_metrics", {})
    rm = ca.get("risk_matrix", {})
    verdict = ca.get("verdict", "UNKNOWN")
    rationale = ca.get("verdict_rationale", "")
    easy_wins = ca.get("easy_wins", [])
    summary = ca.get("summary", {})

    verdict_emoji = {
        "PRODUCTION_READY": "✅",
        "NEEDS_WORK": "⚠️",
        "CRITICAL_GAPS": "❌"
    }.get(verdict, "❓")

    now = datetime.now(timezone.utc).strftime(
        "%Y-%m-%d %H:%M UTC")

    lines = [
        "# BALU Coverage Assessment Report",
        f"Generated: {now}",
        "",
        "## Executive Summary",
        "",
        f"**Verdict: {verdict_emoji} {verdict}**",
        "",
        f"> {rationale}",
        "",
        "## Coverage Metrics",
        "",
        "| Metric | Coverage |",
        "|--------|----------|",
        f"| Address Coverage | "
        f"{m.get('address_coverage_pct', 0):.1f}% |",
        f"| Branch Coverage | "
        f"{m.get('branch_coverage_pct', 0):.1f}% |",
        f"| Branch Coverage (excl. dead code) | "
        f"{m.get('adjusted_branch_pct', 0):.1f}% |",
        f"| Functional Coverage | "
        f"{m.get('functional_coverage_pct', 0):.1f}% |",
        f"| Assertion Coverage | "
        f"{m.get('assertion_coverage_pct', 0):.1f}% |",
        f"| **Overall** | "
        f"**{m.get('overall_pct', 0):.1f}%** |",
        "",
        "## Risk Matrix",
        "",
        "| Category | Count |",
        "|----------|-------|",
        f"| High Risk Gaps | "
        f"{rm.get('high_risk_gaps', 0)} |",
        f"| Medium Risk Gaps | "
        f"{rm.get('medium_risk_gaps', 0)} |",
        f"| Low Risk Gaps | "
        f"{rm.get('low_risk_gaps', 0)} |",
        f"| Real RTL Branch Gaps | "
        f"{rm.get('real_rtl_gaps', 0)} |",
        f"| Phase 2 Gaps | "
        f"{rm.get('phase2_gaps', 0)} |",
        "",
        "## RTL Branch Coverage",
        "",
        f"- Total branches: {cc.get('total_branches', 0)}",
        f"- Exercised: {cc.get('exercised_branches', 0)}",
        f"- Unexercised: "
        f"{cc.get('unexercised_branches', 0)}",
        "",
        "**Classification of unexercised branches:**",
        "",
    ]

    for cls, count in cc.get(
            "uncovered_by_classification", {}).items():
        if count > 0:
            lines.append(f"- {cls}: {count}")

    lines += [
        "",
        "## Assertion Coverage",
        "",
        f"- Total assertions: "
        f"{ac.get('total_assertions', 0)}",
        f"- Dead code (elaboration): "
        f"{ac.get('dead_code', 0)}",
        f"- Untested: {ac.get('untested', 0)}",
        f"- Fired during simulation: "
        f"{ac.get('fired', 0)}",
        f"- Failures detected: "
        f"{ac.get('failures', 0)}",
        "",
        "## Easy Wins",
        "",
    ]

    if easy_wins:
        lines.append(
            "These gaps can be closed with minimal effort:")
        lines.append("")
        lines.append(
            "| Req ID | Family | Covered By | "
            "Action |")
        lines.append(
            "|--------|--------|------------|"
            "--------|")
        for w in easy_wins:
            lines.append(
                f"| {w.get('req_id','')} | "
                f"{w.get('family','')} | "
                f"{w.get('covered_by','')} | "
                f"{w.get('recommended_action','')} |")
    else:
        lines.append(
            "No easy wins identified in current analysis.")
        lines.append("")
        lines.append(
            "> Note: CAE-004 functional analyzer "
            "needs enrichment to populate gap details.")

    lines += [
        "",
        "## Verdict",
        "",
        f"**{verdict_emoji} {verdict}**",
        "",
        summary.get("recommendation", ""),
        "",
        "---",
        "*Generated by pssgen Coverage Assessment Engine*",
    ]

    report = "\n".join(lines)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report)
    return report
