# ===========================================================
# FILE:         agents/scaffold_gen.py
# PROJECT:      pssgen — AI-Driven PSS + UVM + C Testbench Generator
# COPYRIGHT:    Copyright (c) 2026 BelTech Systems LLC
# LICENSE:      MIT License — see LICENSE file for details
# ===========================================================
#
# DESCRIPTION:
#   Generates _generated.intent and _generated.req scaffold files from IR
#   and intent parse results. All machine-inferred lines are tagged with
#   [GENERATED] to distinguish them from human-authored content. Both output
#   files include a human-contribution notice and are never overwritten.
#   Also generates a complete STD-003B UVM testbench file set from IR and
#   an optional VplanParseResult via Python string generation (D-032).
#
# LAYER:        3 — agents
# PHASE:        v3a / D-032
#
# FUNCTIONS:
#   generate_intent_scaffold(ir, intent_result, out_path)
#     Write a _generated.intent scaffold with [GENERATED] port entries and gaps section.
#   generate_req_scaffold(ir, intent_result, out_path)
#     Write a _generated.req scaffold with skeleton entries for each intent req ID.
#   generate_uvm_tb(ir, vplan_result, out_dir)
#     Write all 15 STD-003B UVM testbench files under out_dir/tb/; never overwrites.
#
# DEPENDENCIES:
#   Standard library:  os, logging
#   Internal:          ir
#
# HISTORY:
#   v3a    2026-03-28  SB  Initial implementation; intent and req scaffold generation
#   D-032  2026-04-14  SB  Add generate_uvm_tb() — Python string UVM generation
#                          retiring Jinja2 template-based UVM generation
#
# ===========================================================
"""agents/scaffold_gen.py — Intent, requirements, and UVM testbench scaffold generator.

Phase: v3a / D-032
Layer: 3 (agent)

Generates _generated.intent and _generated.req scaffold files from the IR
and intent parse results. Also generates a complete STD-003B UVM testbench
file set (15 required files) using Python string generation per D-032.

The never-overwrite contract: files are written only when they do not
already exist at the target path. Callers are responsible for enforcing this.
"""
import os
import logging
import datetime
from ir import IR

logger = logging.getLogger(__name__)

# ===========================================================================
# STD-006 file header generators
# ===========================================================================

_SV_SEP = "// " + "=" * 62


def _sv_file_header(
    filename: str,
    brief: str,
    functional_blocks: list,
    dependencies: list,
    portability: str,
    impl_status: str,
    generation_date: str | None = None,
) -> str:
    """Generate a STD-006 compliant SystemVerilog file header.

    Produces the opening comment block that must appear at the top of every
    generated .sv file. Uses // comment syntax and a 62-= separator line.

    Args:
        filename: Bare filename (no path), e.g. ``foo_driver.sv``.
        brief: One or two sentence functional description of the file.
        functional_blocks: List of (block_name, description) tuples.
        dependencies: List of dependency name strings.
        portability: Portability note string, e.g. ``"Simulator-independent"``.
        impl_status: One of generated/stub/partial/complete/validated.
        generation_date: ISO date string (YYYY-MM-DD). Defaults to today.

    Returns:
        Full header string ending with a trailing newline.
    """
    date = generation_date or datetime.date.today().isoformat()
    lines = [
        _SV_SEP,
        f"// File       : {filename}",
        "// Project    : pssgen \u2014 AI-Driven PSS + UVM + C Testbench Generator",
        "// Copyright  : Copyright (c) 2026 BelTech Systems LLC",
        "// License    : MIT License \u2014 see LICENSE for details",
        _SV_SEP,
        f"// Brief      : {brief}",
        "// Document   : BelTech-STD-003 Rev 1",
        "// Standard   : SystemVerilog IEEE 1800-2017 / UVM 1.2",
        "//",
        "// Functional blocks:",
    ]
    for block_name, block_desc in functional_blocks:
        lines.append(f"//   {block_name:<18} : {block_desc}")
    lines.append("//")
    lines.append("// Dependencies:")
    for dep in dependencies:
        lines.append(f"//   {dep}")
    lines.append("//")
    lines.append(f"// Portability    : {portability}")
    lines.append(f"// Impl. status   : {impl_status}")
    lines.append("//")
    lines.append("// History:")
    lines.append(
        f"//   {date}  pssgen  Generated by scaffold_gen.generate_uvm_tb()"
    )
    lines.append(_SV_SEP)
    return "\n".join(lines) + "\n"


_TCL_SEP = "# " + "=" * 62


def _tcl_file_header(
    filename: str,
    brief: str,
    tool: str,
    impl_status: str,
    generation_date: str | None = None,
) -> str:
    """Generate a STD-006 compliant Tcl file header.

    Produces the opening comment block for generated .tcl scripts.
    Uses # comment syntax and a 62-= separator line.

    Args:
        filename: Bare filename (no path), e.g. ``build.tcl``.
        brief: One or two sentence description of the script's purpose.
        tool: Tool and version string, e.g. ``"Vivado 2024.x / XSIM"``.
        impl_status: One of generated/reviewed/validated.
        generation_date: ISO date string (YYYY-MM-DD). Defaults to today.

    Returns:
        Full header string ending with a trailing newline.
    """
    date = generation_date or datetime.date.today().isoformat()
    lines = [
        _TCL_SEP,
        f"# File       : {filename}",
        "# Project    : pssgen \u2014 AI-Driven PSS + UVM + C Testbench Generator",
        "# Copyright  : Copyright (c) 2026 BelTech Systems LLC",
        "# License    : MIT License \u2014 see LICENSE for details",
        _TCL_SEP,
        f"# Brief      : {brief}",
        "# Document   : BelTech-STD-003 Rev 1",
        f"# Tool       : {tool}",
        "#",
        "# Usage:",
        "#   vivado -mode tcl -source build.tcl",
        "#",
        f"# Impl. status   : {impl_status}",
        "#",
        "# History:",
        f"#   {date}  pssgen  Generated by scaffold_gen.generate_uvm_tb()",
        _TCL_SEP,
    ]
    return "\n".join(lines) + "\n"


# Human contribution notice included verbatim in every scaffold file.
_HUMAN_NOTICE = """\
# NOTE: This file was generated by pssgen as a starting point.
# All [GENERATED] entries require human review.
# Entries without [GENERATED] prefix are human-authored.
# This file will never be overwritten by pssgen.
# Copyright in this file, after human review and editing,
# rests with the engineer who reviewed and edited it.
"""

# Roles that are candidates for intent gap detection
_GAP_ROLES = {"control", "data"}


def _infer_intent_gaps(ir: IR, intent_result) -> list[str]:
    """Identify ports whose roles are not covered by intent sections.

    A port is considered covered if its name appears in any section content
    of the intent result (case-insensitive substring match).

    Args:
        ir: Populated IR for the design.
        intent_result: IntentParseResult (or None) from intent parsing.

    Returns:
        List of port names that have no mention in intent sections.
    """
    if intent_result is None:
        # All control/data ports are gaps when no intent was provided
        return [p.name for p in ir.ports if p.role in _GAP_ROLES]

    # Flatten all intent content into a single lowercase string for search
    all_content = " ".join(
        " ".join(lines)
        for lines in intent_result.sections.values()
    ).lower()

    gaps = []
    for port in ir.ports:
        if port.role in _GAP_ROLES:
            if port.name.lower() not in all_content:
                gaps.append(port.name)
    return gaps


def generate_intent_scaffold(ir: IR, intent_result, out_path: str) -> str:
    """Generate a _generated.intent scaffold file.

    Writes a structured intent scaffold with [GENERATED] markers for each
    port, includes existing intent sections if present, and appends an
    intent_gaps section for uncovered ports.

    Args:
        ir: Populated IR for the design.
        intent_result: IntentParseResult from intent parsing, or None if no
            intent file was provided.
        out_path: Full file path to write the scaffold to.

    Returns:
        The file path written (same as out_path).
    """
    gaps = _infer_intent_gaps(ir, intent_result)

    lines: list[str] = []
    lines.append(_HUMAN_NOTICE)
    lines.append(f"# verification intent scaffold: {ir.design_name}")
    lines.append(f"# generated from: {ir.hdl_source}")
    lines.append("")

    # Include existing sections from intent_result (if any)
    if intent_result is not None and intent_result.sections:
        for heading, content_lines in intent_result.sections.items():
            lines.append(f"{heading}:")
            for content_line in content_lines:
                lines.append(f"  {content_line.strip()}")
            lines.append("")

    # Add [GENERATED] port sections
    lines.append("port behaviors:")
    for port in ir.ports:
        role_desc = _role_description(port.role, port.direction, port.width)
        lines.append(
            f"  [GENERATED] {port.name} ({port.direction} {port.width}-bit,"
            f" role={port.role}): {role_desc}"
        )
    lines.append("")

    # Intent gaps section
    if gaps:
        lines.append("intent gaps:")
        for gap_port in gaps:
            lines.append(
                f"  [GENERATED] {gap_port}: no verification intent found —"
                f" human review required"
            )
        lines.append("")

    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    return out_path


def generate_req_scaffold(ir: IR, intent_result, out_path: str) -> str:
    """Generate a _generated.req scaffold file.

    Writes skeleton requirement entries for each ID found in the intent
    result. If no IDs are present, writes a placeholder entry.

    Args:
        ir: Populated IR for the design.
        intent_result: IntentParseResult from intent parsing, or None.
        out_path: Full file path to write the scaffold to.

    Returns:
        The file path written (same as out_path).
    """
    req_ids: list[str] = []
    if intent_result is not None and intent_result.req_ids:
        req_ids = intent_result.req_ids

    lines: list[str] = []
    lines.append(_HUMAN_NOTICE)
    lines.append(f"# requirements scaffold: {ir.design_name}")
    lines.append(f"# generated from: {ir.hdl_source}")
    lines.append("")

    if req_ids:
        for rid in req_ids:
            lines.append(f"[{rid}] [GENERATED] Requirement statement — human review required.")
            lines.append("  verification: simulation")
            lines.append("")
    else:
        lines.append(
            f"[{ir.design_name.upper()}-REQ-001] [GENERATED] "
            "Placeholder requirement — replace with project-specific requirement."
        )
        lines.append("  verification: simulation")
        lines.append("")

    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    return out_path


def _role_description(role: str, direction: str, width: int) -> str:
    """Return a human-readable description hint for a port role.

    Args:
        role: Port role string (clock, reset_n, reset, control, data).
        direction: Port direction (input, output, inout).
        width: Port bit width.

    Returns:
        A short description hint string.
    """
    descriptions = {
        "clock": "synchronous clock — verify all synchronous behavior",
        "reset_n": "active-low reset — verify reset assertion and deassertion",
        "reset": "active-high reset — verify reset assertion and deassertion",
        "control": f"{width}-bit control signal — describe expected behavior",
        "data": f"{width}-bit data {direction} — describe expected values and ranges",
    }
    return descriptions.get(role, f"{width}-bit {direction} — describe expected behavior")


# ===========================================================================
# UVM testbench generation (D-032) — Python string generation
# ===========================================================================

def _port_signal_decl(port) -> str:
    """Return a logic signal declaration line for a non-clock port.

    Args:
        port: Port dataclass with name, direction, width fields.

    Returns:
        SystemVerilog logic declaration string (no trailing newline).
    """
    if port.width == 1:
        return f"    logic {port.name};"
    else:
        return f"    logic [{port.width - 1}:0] {port.name};"


def _gen_if(d: str, ir: IR) -> str:
    """Generate {design}_if.sv content.

    Args:
        d: Design name.
        ir: Populated IR with port list.

    Returns:
        Full file content string.
    """
    clock_port = next((p for p in ir.ports if p.role == "clock"), None)
    non_clock_ports = [p for p in ir.ports if p.role != "clock"]

    header = _sv_file_header(
        filename=f"{d}_if.sv",
        brief=f"AXI-Lite interface bundle for {d} DUT connections.",
        functional_blocks=[
            ("Interface signals", "All DUT ports as logic signals"),
        ],
        dependencies=["UVM 1.2"],
        portability="Simulator-independent",
        impl_status="generated",
    )

    lines = [f"interface {d}_if ("]
    lines.append("    input logic clk")
    lines.append(");")
    lines.append(f"    // Signals mirroring {d} non-clock ports")
    lines.append("")

    # If the DUT has an explicit clock port with a different name than 'clk',
    # add an axi_aclk alias inside the interface for driver/monitor compatibility.
    if clock_port is not None and clock_port.name != "clk":
        lines.append(f"    logic {clock_port.name};")
        lines.append("")

    for port in non_clock_ports:
        if port.width == 1:
            lines.append(f"    logic {port.name};")
        else:
            lines.append(f"    logic [{port.width - 1}:0] {port.name};")
        lines.append("")

    lines.append("endinterface")
    return header + "\n".join(lines)


def _gen_pkg(d: str, cov_stubs: list[str]) -> str:
    """Generate {design}_pkg.sv content.

    Args:
        d: Design name.
        cov_stubs: List of COV stub file basenames (e.g. ['seq_RCOV_001_foo.sv']).

    Returns:
        Full file content string.
    """
    header = _sv_file_header(
        filename=f"{d}_pkg.sv",
        brief=(
            f"{d} UVM package \u2014 includes all TB classes in dependency order."
        ),
        functional_blocks=[
            ("Package", "Single compile unit; enforces include order"),
        ],
        dependencies=[
            "UVM 1.2",
            "all TB class files (see include list below)",
        ],
        portability="Simulator-independent",
        impl_status="generated",
    )

    lines = [
        f"package {d}_pkg;",
        "    // Bring in UVM for the whole package",
        "    import uvm_pkg::*;",
        '    `include "uvm_macros.svh"',
        "",
        "    // Include the class files in strict dependency order",
        f'    `include "{d}_seq_item.sv"            // no dependencies',
        f'    `include "{d}_seqr.sv"                // depends on seq_item',
        f'    `include "{d}_driver.sv"              // depends on seq_item',
        f'    `include "{d}_monitor.sv"             // depends on seq_item',
        f'    `include "{d}_scoreboard.sv"          // depends on seq_item',
        f'    `include "{d}_coverage_subscriber.sv" // depends on seq_item',
        f'    `include "{d}_base_seq.sv"            // depends on seq_item',
        f'    `include "{d}_smoke_seq.sv"           // depends on base_seq',
    ]
    for stub_file in cov_stubs:
        lines.append(f'    `include "{stub_file}"                    // depends on base_seq')
    lines.append(f'    `include "{d}_agent.sv"               // depends on drv/mon/seqr')
    lines.append(f'    `include "{d}_env.sv"                 // depends on agent/sb/cov')
    lines.append(f'    `include "{d}_test.sv"                // depends on env')
    lines.append(f'    `include "{d}_regression_test.sv"     // depends on test + seqs')
    lines.append("endpackage")
    return header + "\n".join(lines)


def _gen_seq_item(d: str) -> str:
    """Generate {design}_seq_item.sv content.

    Args:
        d: Design name.

    Returns:
        Full file content string.
    """
    D = d.upper()
    header = _sv_file_header(
        filename=f"{d}_seq_item.sv",
        brief=(
            f"AXI-Lite transaction sequence item for {d} verification. "
            "Represents one single-beat register access."
        ),
        functional_blocks=[
            ("AXI-Lite transaction model", "cmd/addr/wdata/wstrb/rdata"),
            ("Constraints", "addr alignment, pre-delay, wstrb by cmd"),
        ],
        dependencies=["uvm_pkg"],
        portability="Simulator-independent",
        impl_status="generated",
    )
    return header + f"""`ifndef {D}_SEQ_ITEM_SV
`define {D}_SEQ_ITEM_SV

class {d}_seq_item extends uvm_sequence_item;

    //--------------------------------------------------------------------------
    // Type used to describe the requested bus operation
    //--------------------------------------------------------------------------
    typedef enum logic [0:0] {{
        AXI_READ  = 1'b0,
        AXI_WRITE = 1'b1
    }} axi_cmd_e;

    //--------------------------------------------------------------------------
    // Stimulus fields
    //--------------------------------------------------------------------------
    rand axi_cmd_e    cmd;
    rand bit [31:0]   addr;
    rand bit [31:0]   wdata;
    rand bit [3:0]    wstrb;

    // Optional timing knob for bus stress testing
    rand int unsigned pre_delay_cycles;

    //--------------------------------------------------------------------------
    // Response / observation fields
    //--------------------------------------------------------------------------
    bit [31:0]        rdata;
    bit [1:0]         resp;

    // Optional bookkeeping / checking aids
    string            reg_name;
    bit               expect_error;
    bit [31:0]        expected_rdata;

    //--------------------------------------------------------------------------
    // Constraints
    //--------------------------------------------------------------------------
    // AXI-Lite registers are 32-bit aligned
    constraint c_addr_aligned {{
        addr[1:0] == 2'b00;
    }}

    // Keep delay small by default for fast regression runtime
    constraint c_pre_delay_cycles {{
        pre_delay_cycles inside {{[0:10]}};
    }}

    // Default strobes:
    // - Writes default to full word access
    // - Reads keep strobes at zero
    constraint c_wstrb_by_cmd {{
        if (cmd == AXI_WRITE) {{
            wstrb != 4'b0000;
        }} else {{
            wstrb == 4'b0000;
        }}
    }}

    //--------------------------------------------------------------------------
    // UVM automation
    //--------------------------------------------------------------------------
    `uvm_object_utils_begin({d}_seq_item)
        `uvm_field_enum(axi_cmd_e,  cmd,             UVM_DEFAULT)
        `uvm_field_int(addr,                         UVM_HEX)
        `uvm_field_int(wdata,                        UVM_HEX)
        `uvm_field_int(wstrb,                        UVM_BIN)
        `uvm_field_int(pre_delay_cycles,             UVM_DEC)
        `uvm_field_int(rdata,                        UVM_HEX | UVM_NOCOMPARE)
        `uvm_field_int(resp,                         UVM_BIN | UVM_NOCOMPARE)
        `uvm_field_string(reg_name,                  UVM_DEFAULT)
        `uvm_field_int(expect_error,                 UVM_DEFAULT)
        `uvm_field_int(expected_rdata,               UVM_HEX)
    `uvm_object_utils_end

    //--------------------------------------------------------------------------
    // Constructor
    //--------------------------------------------------------------------------
    function new(string name = "{d}_seq_item");
        super.new(name);
        reg_name        = "";
        expect_error    = 1'b0;
        expected_rdata  = '0;
        rdata           = '0;
        resp            = 2'b00;
    endfunction

    //--------------------------------------------------------------------------
    // Convenience helpers
    //--------------------------------------------------------------------------
    function bit is_read();
        return (cmd == AXI_READ);
    endfunction

    function bit is_write();
        return (cmd == AXI_WRITE);
    endfunction

    //--------------------------------------------------------------------------
    // Convert to readable string for logs / debug
    //--------------------------------------------------------------------------
    function string convert2string();
        string cmd_str;
        cmd_str = (cmd == AXI_WRITE) ? "WRITE" : "READ";

        return $sformatf(
            "cmd=%s addr=0x%08h wdata=0x%08h wstrb=0x%1h pre_delay=%0d rdata=0x%08h resp=0x%0h reg_name=%s expect_error=%0b expected_rdata=0x%08h",
            cmd_str,
            addr,
            wdata,
            wstrb,
            pre_delay_cycles,
            rdata,
            resp,
            reg_name,
            expect_error,
            expected_rdata
        );
    endfunction

    //--------------------------------------------------------------------------
    // Optional helper to set up a write quickly
    //--------------------------------------------------------------------------
    function void set_write(
        bit [31:0] addr_in,
        bit [31:0] data_in,
        bit [3:0]  strb_in = 4'hF,
        string     reg_name_in = ""
    );
        cmd      = AXI_WRITE;
        addr     = addr_in;
        wdata    = data_in;
        wstrb    = strb_in;
        reg_name = reg_name_in;
    endfunction

    //--------------------------------------------------------------------------
    // Optional helper to set up a read quickly
    //--------------------------------------------------------------------------
    function void set_read(
        bit [31:0] addr_in,
        string     reg_name_in = ""
    );
        cmd      = AXI_READ;
        addr     = addr_in;
        wdata    = '0;
        wstrb    = '0;
        reg_name = reg_name_in;
    endfunction

endclass

`endif"""


def _gen_seqr(d: str) -> str:
    """Generate {design}_seqr.sv content.

    Args:
        d: Design name.

    Returns:
        Full file content string.
    """
    header = _sv_file_header(
        filename=f"{d}_seqr.sv",
        brief=f"{d} UVM sequencer \u2014 arbitrates sequence item flow to driver.",
        functional_blocks=[
            ("Sequencer", f"uvm_sequencer parameterised on {d}_seq_item"),
        ],
        dependencies=[f"{d}_seq_item"],
        portability="Simulator-independent",
        impl_status="generated",
    )
    return header + (
        f"class {d}_sequencer extends uvm_sequencer #({d}_seq_item);\n"
        f"    `uvm_component_utils({d}_sequencer)\n"
        "\n"
        f"    function new(string name, uvm_component parent);\n"
        f"        super.new(name, parent);\n"
        f"    endfunction\n"
        f"endclass"
    )


def _gen_base_seq(d: str) -> str:
    """Generate {design}_base_seq.sv content.

    Args:
        d: Design name.

    Returns:
        Full file content string.
    """
    header = _sv_file_header(
        filename=f"{d}_base_seq.sv",
        brief=f"{d} base sequence \u2014 axi_write() and axi_read() helper tasks.",
        functional_blocks=[
            ("axi_write", "Drive a write transaction"),
            ("axi_read", "Drive a read transaction"),
        ],
        dependencies=[f"{d}_seq_item", f"{d}_sequencer"],
        portability="Simulator-independent",
        impl_status="generated",
    )
    return header + f"""class {d}_base_seq extends
    uvm_sequence #({d}_seq_item);

    `uvm_object_utils({d}_base_seq)

    function new(string name = "{d}_base_seq");
        super.new(name);
    endfunction

    // Convenience task: perform one AXI-Lite write and wait for BVALID.
    // The driver handles handshaking; this task just creates and sends
    // the item.
    virtual task axi_write(input bit [31:0] addr,
                           input bit [31:0] data,
                           input bit [3:0]  strb     = 4'hF,
                           input string     reg_name = "");
        {d}_seq_item item;
        item = {d}_seq_item::type_id::create("item");
        start_item(item);
        item.set_write(addr, data, strb, reg_name);
        finish_item(item);
    endtask

    // Convenience task: perform one AXI-Lite read.
    virtual task axi_read(input  bit [31:0] addr,
                          output bit [31:0] rdata,
                          input  string     reg_name = "");
        {d}_seq_item item;
        item = {d}_seq_item::type_id::create("item");
        start_item(item);
        item.set_read(addr, reg_name);
        finish_item(item);
        rdata = item.rdata;
    endtask

endclass"""


def _gen_driver(d: str, ir: IR) -> str:
    """Generate {design}_driver.sv content.

    Generates a driver that initialises all interface signals before
    reset deassertion and then processes items from the sequencer.
    Signal names are derived from the IR port list.

    Args:
        d: Design name.
        ir: Populated IR with port list.

    Returns:
        Full file content string.
    """
    # Find clock and reset ports for interface signal mapping
    clock_port = next((p for p in ir.ports if p.role == "clock"), None)
    reset_port = next(
        (p for p in ir.ports if p.role in ("reset_n", "reset")), None
    )
    clock_sig = clock_port.name if clock_port else "clk"
    reset_sig = reset_port.name if reset_port else "rst_n"
    reset_val = "1'b1" if (reset_port and reset_port.role == "reset_n") else "1'b0"

    header = _sv_file_header(
        filename=f"{d}_driver.sv",
        brief=f"{d} UVM driver \u2014 drives AXI-Lite transactions onto DUT interface.",
        functional_blocks=[
            ("drive_write", "AW/W/B channel handshake"),
            ("drive_read", "AR/R channel handshake"),
        ],
        dependencies=[f"{d}_if", f"{d}_seq_item"],
        portability="Vivado/Questa/Icarus",
        impl_status="generated",
    )
    return header + f"""class {d}_driver extends uvm_driver #({d}_seq_item);
    `uvm_component_utils({d}_driver)

    virtual {d}_if vif;

    function new(string name, uvm_component parent);
        super.new(name, parent);
    endfunction

    function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        if (!uvm_config_db #(virtual {d}_if)::get(
                this, "", "vif", vif))
            `uvm_fatal("NO_VIF",
                "{d}_driver: vif not found in config_db")
    endfunction

    task run_phase(uvm_phase phase);
        {d}_seq_item req;
        // Deassert all driven signals before waiting for reset
        vif.s_axi_awvalid <= 1'b0;
        vif.s_axi_awaddr  <= '0;
        vif.s_axi_awprot  <= '0;
        vif.s_axi_wvalid  <= 1'b0;
        vif.s_axi_wdata   <= '0;
        vif.s_axi_wstrb   <= '0;
        vif.s_axi_bready  <= 1'b0;
        vif.s_axi_arvalid <= 1'b0;
        vif.s_axi_araddr  <= '0;
        vif.s_axi_arprot  <= '0;
        vif.s_axi_rready  <= 1'b0;
        // Wait for reset to deassert before driving any transactions
        @(posedge vif.{clock_sig} iff vif.{reset_sig} === {reset_val});
        forever begin
            seq_item_port.get_next_item(req);
            if (req.cmd === {d}_seq_item::AXI_WRITE)
                drive_write(req);
            else
                drive_read(req);
            seq_item_port.item_done();
        end
    endtask

    // Drive one AXI-Lite write transaction: AW -> W -> B
    task drive_write({d}_seq_item req);
        // Optional pre-delay
        repeat (req.pre_delay_cycles) @(posedge vif.{clock_sig});

        // AW channel: assert awvalid, hold until awready
        @(posedge vif.{clock_sig});
        vif.s_axi_awvalid <= 1'b1;
        vif.s_axi_awaddr  <= req.addr[7:0];
        vif.s_axi_awprot  <= 3'b000;
        @(posedge vif.{clock_sig} iff vif.s_axi_awready === 1'b1);
        vif.s_axi_awvalid <= 1'b0;
        vif.s_axi_awaddr  <= '0;

        // W channel: assert wvalid, hold until wready
        @(posedge vif.{clock_sig});
        vif.s_axi_wvalid <= 1'b1;
        vif.s_axi_wdata  <= req.wdata;
        vif.s_axi_wstrb  <= req.wstrb;
        @(posedge vif.{clock_sig} iff vif.s_axi_wready === 1'b1);
        vif.s_axi_wvalid <= 1'b0;
        vif.s_axi_wdata  <= '0;
        vif.s_axi_wstrb  <= '0;

        // B channel: assert bready, wait for bvalid, capture bresp
        vif.s_axi_bready <= 1'b1;
        @(posedge vif.{clock_sig} iff vif.s_axi_bvalid === 1'b1);
        req.resp = vif.s_axi_bresp;
        @(posedge vif.{clock_sig});
        vif.s_axi_bready <= 1'b0;
    endtask

    // Drive one AXI-Lite read transaction: AR -> R
    task drive_read({d}_seq_item req);
        // Optional pre-delay
        repeat (req.pre_delay_cycles) @(posedge vif.{clock_sig});

        // AR channel: assert arvalid, hold until arready
        @(posedge vif.{clock_sig});
        vif.s_axi_arvalid <= 1'b1;
        vif.s_axi_araddr  <= req.addr[7:0];
        vif.s_axi_arprot  <= 3'b000;
        @(posedge vif.{clock_sig} iff vif.s_axi_arready === 1'b1);
        vif.s_axi_arvalid <= 1'b0;
        vif.s_axi_araddr  <= '0;

        // R channel: assert rready, wait for rvalid, capture rdata and rresp
        vif.s_axi_rready <= 1'b1;
        @(posedge vif.{clock_sig} iff vif.s_axi_rvalid === 1'b1);
        req.rdata = vif.s_axi_rdata;
        req.resp  = vif.s_axi_rresp;
        @(posedge vif.{clock_sig});
        vif.s_axi_rready <= 1'b0;
    endtask

endclass"""


def _gen_monitor(d: str, ir: IR) -> str:
    """Generate {design}_monitor.sv content.

    Args:
        d: Design name.
        ir: Populated IR with port list.

    Returns:
        Full file content string.
    """
    clock_port = next((p for p in ir.ports if p.role == "clock"), None)
    reset_port = next(
        (p for p in ir.ports if p.role in ("reset_n", "reset")), None
    )
    clock_sig = clock_port.name if clock_port else "clk"
    reset_sig = reset_port.name if reset_port else "rst_n"
    reset_val = "1'b1" if (reset_port and reset_port.role == "reset_n") else "1'b0"

    header = _sv_file_header(
        filename=f"{d}_monitor.sv",
        brief=(
            f"{d} UVM monitor \u2014 observes AXI-Lite transactions and "
            "publishes to analysis port."
        ),
        functional_blocks=[
            ("Monitor run_phase", "Latch AW/W/AR, publish completed transactions"),
        ],
        dependencies=[f"{d}_if", f"{d}_seq_item"],
        portability="Simulator-independent",
        impl_status="generated",
    )
    return header + f"""class {d}_monitor extends uvm_monitor;
    `uvm_component_utils({d}_monitor)

    virtual {d}_if              vif;
    uvm_analysis_port #({d}_seq_item) ap;

    function new(string name, uvm_component parent);
        super.new(name, parent);
    endfunction

    function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        ap = new("ap", this);
        if (!uvm_config_db #(virtual {d}_if)::get(
                this, "", "vif", vif))
            `uvm_fatal("NO_VIF",
                "{d}_monitor: vif not found in config_db")
    endfunction

    task run_phase(uvm_phase phase);
        {d}_seq_item item;
        // Latches for channel data — populated on handshake, used at response
        bit [7:0]  aw_addr_lat_s;
        bit [31:0] wd_data_lat_s;
        bit [3:0]  wd_strb_lat_s;
        bit [7:0]  ar_addr_lat_s;

        @(posedge vif.{clock_sig} iff vif.{reset_sig} === {reset_val});

        forever begin
            @(posedge vif.{clock_sig});

            // Latch AW handshake address
            if (vif.s_axi_awvalid === 1'b1 && vif.s_axi_awready === 1'b1)
                aw_addr_lat_s = vif.s_axi_awaddr;

            // Latch W handshake data and strobe
            if (vif.s_axi_wvalid === 1'b1 && vif.s_axi_wready === 1'b1) begin
                wd_data_lat_s = vif.s_axi_wdata;
                wd_strb_lat_s = vif.s_axi_wstrb;
            end

            // Completed write: B handshake
            if (vif.s_axi_bvalid === 1'b1 && vif.s_axi_bready === 1'b1) begin
                item = {d}_seq_item::type_id::create("mon_wr");
                item.cmd   = {d}_seq_item::AXI_WRITE;
                item.addr  = {{24'b0, aw_addr_lat_s}};
                item.wdata = wd_data_lat_s;
                item.wstrb = wd_strb_lat_s;
                item.resp  = vif.s_axi_bresp;
                ap.write(item);
            end

            // Latch AR handshake address
            if (vif.s_axi_arvalid === 1'b1 && vif.s_axi_arready === 1'b1)
                ar_addr_lat_s = vif.s_axi_araddr;

            // Completed read: R handshake
            if (vif.s_axi_rvalid === 1'b1 && vif.s_axi_rready === 1'b1) begin
                item = {d}_seq_item::type_id::create("mon_rd");
                item.cmd   = {d}_seq_item::AXI_READ;
                item.addr  = {{24'b0, ar_addr_lat_s}};
                item.rdata = vif.s_axi_rdata;
                item.resp  = vif.s_axi_rresp;
                ap.write(item);
            end
        end
    endtask

endclass"""


def _gen_agent(d: str) -> str:
    """Generate {design}_agent.sv content.

    Args:
        d: Design name.

    Returns:
        Full file content string.
    """
    header = _sv_file_header(
        filename=f"{d}_agent.sv",
        brief=f"{d} UVM agent \u2014 instantiates driver, monitor, and sequencer.",
        functional_blocks=[
            ("build_phase", "Create drv/mon/seqr"),
            ("connect_phase", "Wire seq_item_port to seq_item_export"),
        ],
        dependencies=[f"{d}_driver", f"{d}_monitor", f"{d}_sequencer"],
        portability="Simulator-independent",
        impl_status="generated",
    )
    return header + f"""class {d}_agent extends uvm_agent;
    `uvm_component_utils({d}_agent)

    {d}_driver     drv;
    {d}_monitor    mon;
    {d}_sequencer  seqr;

    function new(string name, uvm_component parent);
        super.new(name, parent);
    endfunction

    function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        drv  = {d}_driver::type_id::create("drv",  this);
        mon  = {d}_monitor::type_id::create("mon", this);
        seqr = {d}_sequencer::type_id::create("seqr", this);
    endfunction

    function void connect_phase(uvm_phase phase);
        drv.seq_item_port.connect(seqr.seq_item_export);
        // mon.ap is connected to sb and cov in env.sv connect_phase
    endfunction

endclass"""


def _gen_scoreboard(d: str, vplan_result) -> str:
    """Generate {design}_scoreboard.sv content.

    If vplan_result provides register map data, pre-loads shadow registers
    from it. Otherwise emits an empty shadow with a UVM_WARNING.

    Args:
        d: Design name.
        vplan_result: VplanParseResult or None.

    Returns:
        Full file content string.
    """
    # Build shadow init body from vplan register map if available
    shadow_lines: list[str] = []
    has_regmap = False

    if vplan_result is not None and hasattr(vplan_result, "register_map"):
        reg_map = vplan_result.register_map
        if reg_map and isinstance(reg_map, dict):
            registers = reg_map.get("registers", [])
            if registers:
                has_regmap = True
                for reg in registers:
                    offset = reg.get("offset", "0x00")
                    # Normalise offset to a padded hex literal
                    try:
                        offset_int = int(offset, 16) if isinstance(offset, str) else int(offset)
                        offset_str = f"32'h{offset_int:08X}"
                    except (ValueError, TypeError):
                        offset_str = "32'h00000000"
                    name = reg.get("name", "UNKNOWN")
                    shadow_lines.append(
                        f"        shadow[{offset_str}] = 32'h00000000;   // {name} reset value"
                    )

    if has_regmap:
        init_body = "\n".join(shadow_lines) if shadow_lines else "        // no RW registers found"
    else:
        init_body = (
            "        `uvm_warning(\"SB\",\n"
            "            \"Shadow register map not available — scoreboard checks disabled\")"
        )

    header = _sv_file_header(
        filename=f"{d}_scoreboard.sv",
        brief=(
            f"{d} UVM scoreboard \u2014 AXI-Lite register shadow model "
            "and response checker."
        ),
        functional_blocks=[
            ("_init_shadow", "Populate shadow from VPR register map"),
            ("write()", "Compare read data against shadow; check write responses"),
        ],
        dependencies=[f"{d}_seq_item", "vplan register map"],
        portability="Simulator-independent",
        impl_status="generated",
    )
    return header + f"""class {d}_scoreboard extends uvm_scoreboard;
    `uvm_component_utils({d}_scoreboard)

    uvm_analysis_imp #({d}_seq_item,
                       {d}_scoreboard) analysis_export;

    // Shadow register model — RW registers only.
    // RO and WO registers are not predicted here.
    local bit [31:0] shadow [bit [31:0]];

    // Running error count reported in check_phase.
    local int error_count;

    function new(string name, uvm_component parent);
        super.new(name, parent);
        error_count = 0;
    endfunction

    function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        analysis_export = new("analysis_export", this);
        _init_shadow();
    endfunction

    // Pre-load RW register reset values.
    local function void _init_shadow();
{init_body}
    endfunction

    // Apply a write to the shadow, honouring wstrb byte-enable masking.
    local function void _apply_write(
        bit [31:0] addr,
        bit [31:0] wdata,
        bit [3:0]  wstrb
    );
        for (int b = 0; b < 4; b++) begin
            if (wstrb[b])
                shadow[addr][b*8 +: 8] = wdata[b*8 +: 8];
        end
    endfunction

    function void write({d}_seq_item item);
        if (item.cmd === {d}_seq_item::AXI_WRITE) begin

            if (item.resp !== 2'b00) begin
                error_count++;
                `uvm_error("SB", $sformatf(
                    "write response not OKAY — addr=0x%08h resp=%02b",
                    item.addr, item.resp))
            end

            if (shadow.exists(item.addr))
                _apply_write(item.addr, item.wdata, item.wstrb);

        end else begin  // AXI_READ

            if (item.resp !== 2'b00) begin
                error_count++;
                `uvm_error("SB", $sformatf(
                    "read response not OKAY — addr=0x%08h resp=%02b",
                    item.addr, item.resp))
            end

            if (shadow.exists(item.addr)) begin
                if (item.rdata !== shadow[item.addr]) begin
                    error_count++;
                    `uvm_error("SB", $sformatf(
                        "register readback mismatch — addr=0x%08h expected=0x%08h actual=0x%08h",
                        item.addr, shadow[item.addr], item.rdata))
                end
            end
        end
    endfunction

    function void check_phase(uvm_phase phase);
        `uvm_info("SB", $sformatf(
            "Scoreboard check_phase: %0d error(s)", error_count), UVM_MEDIUM)
    endfunction

endclass"""


def _gen_coverage_subscriber(d: str, vplan_result) -> str:
    """Generate {design}_coverage_subscriber.sv content.

    Args:
        d: Design name.
        vplan_result: VplanParseResult or None; used for named register bins.

    Returns:
        Full file content string.
    """
    # Build cp_addr bins from register map if available
    addr_bins_lines: list[str] = []
    has_bins = False

    if vplan_result is not None and hasattr(vplan_result, "register_map"):
        reg_map = vplan_result.register_map
        if reg_map and isinstance(reg_map, dict):
            registers = reg_map.get("registers", [])
            if registers:
                has_bins = True
                for reg in registers:
                    offset = reg.get("offset", "0x00")
                    try:
                        offset_int = int(offset, 16) if isinstance(offset, str) else int(offset)
                        offset_str = f"8'h{offset_int:02X}"
                    except (ValueError, TypeError):
                        offset_str = "8'h00"
                    name = reg.get("name", "UNKNOWN")
                    addr_bins_lines.append(
                        f"            bins {name:<16} = {{{offset_str}}};"
                    )

    if has_bins:
        cp_addr_body = "\n".join(addr_bins_lines)
    else:
        cp_addr_body = "            bins addr_default = {default};"

    header = _sv_file_header(
        filename=f"{d}_coverage_subscriber.sv",
        brief=f"{d} UVM coverage subscriber \u2014 functional coverage collection.",
        functional_blocks=[
            ("axi_transaction_cg", "cp_cmd, cp_addr, cp_resp, cross"),
        ],
        dependencies=[f"{d}_seq_item"],
        portability="Simulator-independent",
        impl_status="generated",
    )
    return header + f"""class {d}_coverage_subscriber extends
    uvm_subscriber #({d}_seq_item);

    `uvm_component_utils({d}_coverage_subscriber)

    // Current transaction — updated before each sample() call.
    {d}_seq_item item_s;

    covergroup axi_transaction_cg;

        // Confirms bidirectional bus traffic: both READ and WRITE must be hit.
        cp_cmd: coverpoint item_s.cmd {{
            bins AXI_WRITE = {{{d}_seq_item::AXI_WRITE}};
            bins AXI_READ  = {{{d}_seq_item::AXI_READ}};
        }}

        // One named bin per register — confirms each register was accessed.
        cp_addr: coverpoint item_s.addr[7:0] {{
{cp_addr_body}
        }}

        // Unhit SLVERR bin is informative — shows no error responses seen.
        cp_resp: coverpoint item_s.resp {{
            bins OKAY   = {{2'b00}};
            bins SLVERR = {{2'b10}};
        }}

        // Cross: confirms every register was both read and written where
        // access type permits. Unhit bins for RO/WO registers are expected.
        cp_cmd_x_addr: cross cp_cmd, cp_addr;

    endgroup

    function new(string name, uvm_component parent);
        super.new(name, parent);
        // Vivado requires embedded covergroups to be instantiated in new(),
        // not in build_phase (VRFC 10-8922).
        axi_transaction_cg = new();
    endfunction

    function void build_phase(uvm_phase phase);
        super.build_phase(phase);
    endfunction

    virtual function void write({d}_seq_item t);
        item_s = t;
        axi_transaction_cg.sample();
    endfunction

    function void report_phase(uvm_phase phase);
        `uvm_info("COV",
            $sformatf("axi_transaction_cg coverage: %.1f%%",
                axi_transaction_cg.get_coverage()),
            UVM_MEDIUM)
    endfunction

endclass"""


def _gen_env(d: str) -> str:
    """Generate {design}_env.sv content.

    Args:
        d: Design name.

    Returns:
        Full file content string.
    """
    header = _sv_file_header(
        filename=f"{d}_env.sv",
        brief=(
            f"{d} UVM environment \u2014 top-level env instantiating agent, "
            "scoreboard, and coverage."
        ),
        functional_blocks=[
            ("connect_phase", "Wire monitor AP to scoreboard and coverage subscriber"),
        ],
        dependencies=[f"{d}_agent", f"{d}_scoreboard", f"{d}_coverage_subscriber"],
        portability="Simulator-independent",
        impl_status="generated",
    )
    return header + f"""class {d}_env extends uvm_env;
    `uvm_component_utils({d}_env)

    {d}_agent                   agent;
    {d}_scoreboard              sb;
    {d}_coverage_subscriber     cov;

    function new(string name, uvm_component parent);
        super.new(name, parent);
    endfunction

    function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        agent = {d}_agent::type_id::create("agent", this);
        sb    = {d}_scoreboard::type_id::create("sb", this);
        cov   = {d}_coverage_subscriber::type_id::create("cov", this);
    endfunction

    function void connect_phase(uvm_phase phase);
        agent.mon.ap.connect(sb.analysis_export);
        agent.mon.ap.connect(cov.analysis_export);
    endfunction

endclass"""


def _gen_test(d: str) -> str:
    """Generate {design}_test.sv content (two classes: base_test + smoke_test).

    Args:
        d: Design name.

    Returns:
        Full file content string.
    """
    header = _sv_file_header(
        filename=f"{d}_test.sv",
        brief=f"{d} base and smoke test classes.",
        functional_blocks=[
            (f"{d}_base_test", "Base test; virtual run_sequences()"),
            (f"{d}_smoke_test", "Single write+read smoke sequence"),
        ],
        dependencies=[f"{d}_env", f"{d}_smoke_seq"],
        portability="Simulator-independent",
        impl_status="generated",
    )
    return header + f"""// Base test: owns the env and provides the raise/drop objection wrapper.
// Subclasses override run_sequences() to supply stimulus.
class {d}_base_test extends uvm_test;
    `uvm_component_utils({d}_base_test)

    {d}_env env_h;

    function new(string name, uvm_component parent);
        super.new(name, parent);
    endfunction

    function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        env_h = {d}_env::type_id::create("env_h", this);
    endfunction

    task run_phase(uvm_phase phase);
        phase.raise_objection(this);
        run_sequences(phase);
        phase.drop_objection(this);
    endtask

    // Override in subclass to run sequences. Base does nothing.
    virtual task run_sequences(uvm_phase phase);
    endtask

endclass


// Smoke test: runs {d}_smoke_seq end-to-end.
// Start with: +UVM_TESTNAME={d}_smoke_test
class {d}_smoke_test extends {d}_base_test;
    `uvm_component_utils({d}_smoke_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
    endfunction

    virtual task run_sequences(uvm_phase phase);
        {d}_smoke_seq seq;
        seq = {d}_smoke_seq::type_id::create("seq");
        seq.start(env_h.agent.seqr);
    endtask

endclass"""


def _gen_smoke_seq(d: str) -> str:
    """Generate {design}_smoke_seq.sv content.

    Args:
        d: Design name.

    Returns:
        Full file content string.
    """
    header = _sv_file_header(
        filename=f"{d}_smoke_seq.sv",
        brief=f"{d} smoke sequence \u2014 single AXI-Lite write/read to first RW register.",
        functional_blocks=[
            ("body", "One write, one read, readback assertion"),
        ],
        dependencies=[f"{d}_base_seq"],
        portability="Simulator-independent",
        impl_status="generated",
    )
    return header + f"""class {d}_smoke_seq extends
    {d}_base_seq;

    `uvm_object_utils({d}_smoke_seq)

    function new(string name = "{d}_smoke_seq");
        super.new(name);
    endfunction

    virtual task body();
        bit [31:0] rdata;
        // Write a known value to the first register (offset 0x00)
        axi_write(32'h00000000, 32'h00000000, 4'hF, "REG_0");
        // Read it back
        axi_read(32'h00000000, rdata, "REG_0");
        `uvm_info("SMOKE_SEQ",
            $sformatf("REG_0 readback = 0x%08h", rdata),
            UVM_MEDIUM)
    endtask

endclass"""


def _gen_regression_test(d: str, cov_stubs: list[tuple[str, str]]) -> str:
    """Generate {design}_regression_test.sv content.

    Args:
        d: Design name.
        cov_stubs: List of (class_name, var_name) tuples for COV sequences.

    Returns:
        Full file content string.
    """
    decl_lines: list[str] = []
    create_lines: list[str] = []
    start_lines: list[str] = []

    decl_lines.append(f"        {d}_smoke_seq  smoke;")
    create_lines.append(
        f'        smoke  = {d}_smoke_seq::type_id::create("smoke");'
    )
    start_lines.append(f"        smoke.start(env_h.agent.seqr);")

    for class_name, var_name in cov_stubs:
        decl_lines.append(f"        {class_name}           {var_name};")
        create_lines.append(
            f'        {var_name} = {class_name}::type_id::create("{var_name}");'
        )
        start_lines.append(f"        {var_name}.start(env_h.agent.seqr);")

    decl_block = "\n".join(decl_lines)
    create_block = "\n".join(create_lines)
    start_block = "\n".join(start_lines)

    header = _sv_file_header(
        filename=f"{d}_regression_test.sv",
        brief=f"{d} regression test \u2014 runs smoke sequence then all COV sequence stubs.",
        functional_blocks=[
            ("run_sequences", "Smoke + all COV stubs"),
        ],
        dependencies=[f"{d}_base_test", "all COV seq stubs"],
        portability="Simulator-independent",
        impl_status="generated",
    )
    return header + f"""// Regression test: runs smoke sequence followed by all COV sequences.
// Additional COV sequences are added here as they are created.
// Start with: +UVM_TESTNAME={d}_regression_test
class {d}_regression_test extends {d}_base_test;
    `uvm_component_utils({d}_regression_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
    endfunction

    virtual task run_sequences(uvm_phase phase);
{decl_block}

{create_block}

{start_block}
    endtask

endclass"""


def parse_vsl_stimulus(vsl_string) -> list[dict]:
    """Parse a VSL stimulus string into a list of step dicts.

    VSL grammar (D-034): <step> (";" <step>)* where each step is
    <action> ("," <key>=<value>)*. Empty or "NONE" input returns [].

    Args:
        vsl_string: VSL string from Stimulus_VSL column, or None.

    Returns:
        List of dicts with keys "action" (str) and "params" (dict[str,str]).

    Raises:
        ValueError: If any step cannot be parsed per VSL grammar.
    """
    import re as _re
    _IDENT = _re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

    if vsl_string is None:
        return []
    s = str(vsl_string).strip()
    if not s or s.upper() == "NONE":
        return []

    steps = []
    for raw_step in s.split(";"):
        raw_step = raw_step.strip()
        if not raw_step:
            continue
        parts = [p.strip() for p in raw_step.split(",")]
        action = parts[0]
        if not _IDENT.match(action):
            raise ValueError(
                f"VSL parse error: invalid action {action!r} in step {raw_step!r}"
            )
        params: dict = {}
        for part in parts[1:]:
            if not part:
                raise ValueError(
                    f"VSL parse error: empty param field in step {raw_step!r}"
                )
            if "=" not in part:
                raise ValueError(
                    f"VSL parse error: param {part!r} has no '=' in step {raw_step!r}"
                )
            key, _, value = part.partition("=")
            key = key.strip()
            value = value.strip()
            if not _IDENT.match(key):
                raise ValueError(
                    f"VSL parse error: invalid key {key!r} in step {raw_step!r}"
                )
            params[key] = value
        steps.append({"action": action, "params": params})
    return steps


def _cov_stub_names(cov_item) -> tuple[str, str, str]:
    """Derive class name, var name, and file name from a COV item.

    Naming convention (STD-003B): seq_RCOV<NNN>_<name>
    where NNN is the zero-padded numeric part of the COV ID.
    COV-001 -> seq_RCOV001_baud_tuning
    COV-010 -> seq_RCOV010_axi_bresp

    Args:
        cov_item: Object with .id and .name attributes.

    Returns:
        Tuple of (class_name, var_name, file_basename).
        E.g. ('seq_RCOV001_baud_tuning', 'cov001', 'seq_RCOV001_baud_tuning.sv')
    """
    import re as _re
    # Extract the numeric suffix from IDs like 'COV-001', 'COV-010'
    m = _re.search(r"(\d+)$", cov_item.id)
    num_str = m.group(1).zfill(3) if m else cov_item.id.replace("-", "")

    # Sanitize name: lowercase, spaces/hyphens/dots/ampersands -> underscore,
    # collapse multiple underscores, strip leading/trailing underscores.
    name_raw = cov_item.name.lower()
    name_safe = _re.sub(r"[^a-z0-9]+", "_", name_raw).strip("_")

    class_name = f"seq_RCOV{num_str}_{name_safe}"
    var_name = f"cov{num_str}"
    file_name = f"{class_name}.sv"
    return class_name, var_name, file_name


_BALU_ADDR_MAP: dict[int, str] = {
    0x00: "CTRL",
    0x04: "STATUS",
    0x08: "BAUD",
    0x0C: "TX_DATA",
    0x10: "RX_DATA",
    0x14: "TX_FIFO",
    0x18: "RX_FIFO",
    0x1C: "IER",
    0x20: "ISR",
    0x24: "PARITY",
    0x28: "FRAME",
    0x2C: "SCRATCH",
    0x30: "TIMEOUT",
    0x34: "LOOPBACK",
}


def _addr_to_reg(addr: str) -> str:
    """Convert a hex address string to a register model field name.

    Looks up the BALU register map first. Known addresses return the real
    register name (e.g. "0x08" → "BAUD"). Unknown addresses fall back to a
    reg_XXXX placeholder and emit a WARNING so the caller knows a manual
    fix is needed.

    Args:
        addr: Hex address string, e.g. "0x08" or "0x3C".

    Returns:
        Register name string ("BAUD") or placeholder ("reg_003c").
    """
    import re as _re
    m = _re.match(r"0[xX]([0-9A-Fa-f]+)$", addr.strip())
    if m:
        addr_int = int(m.group(1), 16)
        if addr_int in _BALU_ADDR_MAP:
            return _BALU_ADDR_MAP[addr_int]
        placeholder = f"reg_{addr_int:04x}"
        logger.warning(
            "_addr_to_reg: unknown address %s → %s (placeholder — manual wiring required)",
            addr.strip(), placeholder,
        )
        return placeholder
    clean = addr.strip().lower().lstrip("0x").zfill(4)
    placeholder = f"reg_{clean}"
    logger.warning(
        "_addr_to_reg: non-hex address %r → %s (placeholder — manual wiring required)",
        addr, placeholder,
    )
    return placeholder


def _render_vsl_body(item) -> list[str]:
    """Render UVM body() task content lines from item.vsl_steps.

    Generates reg_write / reg_read / reg_poll calls that delegate to the
    helper tasks in axi4_lite_base_seq. POLL is self-contained via reg_poll;
    only READ steps require a local rdata variable.

    Args:
        item: Object with .vsl_steps (list[dict]) populated by parse_vsl_stimulus.

    Returns:
        List of indented SV lines for insertion inside a body() task.
    """
    steps = item.vsl_steps
    needs_rdata = any(s["action"] == "READ" for s in steps)

    lines: list[str] = []
    if needs_rdata:
        lines.append("        uvm_reg_data_t rdata;")

    for i, step in enumerate(steps, 1):
        action = step["action"]
        params = step["params"]
        lines.append(f"        // Step {i}: {action}")

        if action == "WRITE":
            addr = params.get("addr", "0x0000")
            data = params.get("data", "0x0")
            reg = _addr_to_reg(addr)
            lines.append(f"        reg_write(reg_model.{reg}, {data});")

        elif action == "READ":
            addr = params.get("addr", "0x0000")
            expect = params.get("expect")
            reg = _addr_to_reg(addr)
            lines.append(f"        reg_read(reg_model.{reg}, rdata);")
            if expect is not None:
                lines.append(
                    f"        `uvm_info(get_name(), "
                    f'$sformatf("Read 0x%0h, expect 0x%0h", rdata, {expect}), UVM_LOW)'
                )

        elif action == "WAIT":
            cycles = params.get("cycles", "1")
            lines.append(f"        repeat({cycles}) @(posedge vif.clk);")

        elif action == "POLL":
            addr    = params.get("addr", "0x0000")
            mask    = params.get("mask", "0xFFFFFFFF")
            expect  = params.get("expect", "0x0")
            timeout = params.get("timeout", "1000")
            reg = _addr_to_reg(addr)
            lines.append(f"        reg_poll(reg_model.{reg}, {mask}, {expect}, {timeout});")

        else:
            lines.append(f"        // Unrecognized VSL action: {action}")

    return lines


def _gen_cov_stub(d: str, cov_item) -> str:
    """Generate a COV sequence stub file content.

    Args:
        d: Design name.
        cov_item: Object with .id, .name, .linked_requirements,
                  .stimulus_strategy, .boundary_values attributes.

    Returns:
        Full file content string.
    """
    class_name, _, _ = _cov_stub_names(cov_item)
    cov_id = getattr(cov_item, "id", "")
    cov_name = getattr(cov_item, "name", "")
    linked_reqs = getattr(cov_item, "linked_requirements", []) or []
    strat = getattr(cov_item, "stimulus_strategy", "") or ""
    boundary = getattr(cov_item, "boundary_values", "") or ""
    seq_status = getattr(cov_item, "seq_status", "NONE") or "NONE"
    vsl_steps = getattr(cov_item, "vsl_steps", None) or []
    seq_review = getattr(cov_item, "seq_review", "DRAFT") or "DRAFT"

    req_str = ", ".join(linked_reqs) if linked_reqs else "(none)"

    if seq_review != "APPROVED":
        logger.warning(
            "Skipping VSL body for %s: Seq_Review=%s (not APPROVED)", cov_id, seq_review
        )

    if seq_status == "PHASE_1" and vsl_steps and seq_review == "APPROVED":
        impl_status_val = "phase_1_generated"
        body_label = f"body (PHASE_1 — {len(vsl_steps)} VSL step(s))"
        body_desc = f"Generated from Stimulus_VSL — {cov_id}"
        body_lines = _render_vsl_body(cov_item)
        body_block = (
            "    virtual task body();\n"
            + "\n".join(body_lines)
            + "\n    endtask : body"
        )
    else:
        impl_status_val = "stub"
        body_label = "body (SEQ_PENDING)"
        body_desc = f"Stub \u2014 see VPR {cov_id} for implementation guidance"
        body_block = (
            "    virtual task body();\n"
            f'        `uvm_info("SEQ_PENDING",\n'
            f'            "{class_name}: body not yet implemented \u2014 see VPR {cov_id}",\n'
            f"            UVM_MEDIUM)\n"
            "    endtask"
        )

    header = _sv_file_header(
        filename=f"{class_name}.sv",
        brief=(
            f"COV sequence stub for {cov_id}: {cov_name} \u2014 "
            "implement per VPR Stimulus_Strategy."
        ),
        functional_blocks=[(body_label, body_desc)],
        dependencies=[f"{d}_base_seq"],
        portability="Simulator-independent",
        impl_status=impl_status_val,
    )
    return header + f"""// Linked requirements: {req_str}
// Stimulus strategy  : {strat}
// Boundary values    : {boundary}

class {class_name} extends axi4_lite_base_seq;

    `uvm_object_utils({class_name})

    function new(string name = "{class_name}");
        super.new(name);
    endfunction

{body_block}

endclass"""


def _gen_tb_top(d: str, ir: IR) -> str:
    """Generate tb_top.sv content.

    Args:
        d: Design name.
        ir: Populated IR with port list.

    Returns:
        Full file content string.
    """
    clock_port = next((p for p in ir.ports if p.role == "clock"), None)
    reset_port = next(
        (p for p in ir.ports if p.role in ("reset_n", "reset")), None
    )
    clock_name = clock_port.name if clock_port else "clk"
    reset_name = reset_port.name if reset_port else "rst_n"
    is_active_low = (reset_port is None or reset_port.role == "reset_n")

    # Build DUT port connection list
    port_conns: list[str] = []
    for port in ir.ports:
        if port.role == "clock":
            port_conns.append(f"        .{port.name}(clk)")
        else:
            port_conns.append(f"        .{port.name}(intf.{port.name})")

    port_conn_str = ",\n".join(port_conns)

    # Signal initialisation — set all non-clock signals to 0, uart_rx to 1
    init_lines: list[str] = []
    for port in ir.ports:
        if port.role == "clock":
            continue
        if port.name == "uart_rx":
            init_lines.append(f"        intf.{port.name} = 1'b1;")
        else:
            init_lines.append(f"        intf.{port.name} = '0;")

    init_block = "\n".join(init_lines) if init_lines else "        // no signals to initialise"

    # Clock-to-interface mapping
    if clock_name != "clk":
        clock_map = f"    always_comb intf.{clock_name} = clk;"
    else:
        clock_map = f"    // clk drives intf directly via the interface port"

    # Reset generation
    if is_active_low:
        reset_init = f"        intf.{reset_name} = 1'b0;"
        reset_deassert = f"        intf.{reset_name} = 1'b1;"
    else:
        reset_init = f"        intf.{reset_name} = 1'b1;"
        reset_deassert = f"        intf.{reset_name} = 1'b0;"

    header = _sv_file_header(
        filename="tb_top.sv",
        brief=(
            "tb_top \u2014 top-level testbench module; DUT instantiation, "
            "clock/reset, UVM run_test()."
        ),
        functional_blocks=[
            ("DUT instantiation", "All ports connected via interface"),
            ("Clock/reset", "100 MHz clock; synchronous active-low reset"),
            ("UVM config_db", "Virtual interface registration"),
        ],
        dependencies=["uvm_pkg", f"{d}_pkg", f"{d}_if"],
        portability="Vivado/Questa/Icarus",
        impl_status="generated",
    )
    return header + f"""`timescale 1ns/1ps
module tb_top;
    import uvm_pkg::*;
    import {d}_pkg::*;
    `include "uvm_macros.svh"

    // Free-running clock
    logic clk;
    initial clk = 1'b0;
    always #5 clk = ~clk;

    // Interface instance
    {d}_if intf(.clk(clk));

    // DUT instantiation
    {d} dut (
{port_conn_str}
    );

{clock_map}

    initial begin
        // Initialise all interface signals
{init_block}
        // Hold reset for 10 clock cycles then deassert
        {reset_init}
        repeat (10) @(posedge clk);
        {reset_deassert}
    end

    // Pass virtual interface to UVM config_db
    initial begin
        uvm_config_db #(virtual {d}_if)::set(null, "uvm_test_top.*", "vif", intf);
        run_test();
    end

    // Waveform dump
    initial begin
        $dumpfile("tb_top.vcd");
        $dumpvars(0, tb_top);
    end

endmodule"""


def _gen_build_tcl(d: str, ir: IR) -> str:
    """Generate scripts/vivado/build.tcl content.

    Args:
        d: Design name.
        ir: Populated IR (used for HDL language detection).

    Returns:
        Full file content string.
    """
    is_vhdl = (ir.hdl_language.lower() in ("vhdl", "vhd"))
    if is_vhdl:
        dut_compile = (
            "puts \"--- Compiling DUT ---\"\n"
            "run_cmd [list xvhdl --2008 --work work \\\n"
            "    [file join $DUT_DIR vhdl/${DESIGN}.vhd]]"
        )
    else:
        dut_compile = (
            "puts \"--- Compiling DUT ---\"\n"
            "run_cmd [list xvlog --sv --work work \\\n"
            "    [file join $DUT_DIR ${DESIGN}.sv]]"
        )

    header = _tcl_file_header(
        filename="build.tcl",
        brief=(
            f"{d} Vivado/XSIM build and run script \u2014 "
            "three-file compile model per STD-003."
        ),
        tool="Vivado 2024.x / XSIM",
        impl_status="generated",
    )
    return header + f"""set DESIGN   {d}
set SNAPSHOT ${{DESIGN}}_snapshot

set SCRIPT_DIR [file dirname [file normalize [info script]]]
set TB_DIR     [file join $SCRIPT_DIR ../..]
set DUT_DIR    [file join $SCRIPT_DIR ../../..]
set REPO_ROOT  [file join $DUT_DIR ..]
set SIM_LIB    [file join $REPO_ROOT sim lib]

proc run_cmd {{cmd}} {{
    if {{[catch {{exec {{*}}$cmd >@stdout 2>@stderr}} msg]}} {{
        puts "ERROR: Command failed:"
        puts "  $cmd"
        puts $msg
        exit 1
    }}
}}

{dut_compile}

puts "--- Compiling BFM library (interface first, then package) ---"
run_cmd [list xvlog --sv --uvm_version 1.2 -L uvm --work work \\
    --include $REPO_ROOT \\
    [file join $SIM_LIB bfm axi4_lite_if.sv] \\
    [file join $SIM_LIB pkg bfm_pkg.sv]]

puts "--- Compiling UVM TB ---"
run_cmd [list xvlog --sv --uvm_version 1.2 -L uvm --work work \\
    --include $TB_DIR \\
    --include $REPO_ROOT \\
    [file join $TB_DIR ${{DESIGN}}_if.sv] \\
    [file join $TB_DIR ${{DESIGN}}_pkg.sv] \\
    [file join $TB_DIR tb_top.sv]]

puts "--- Elaborating ---"
run_cmd [list xelab -L uvm \\
    work.tb_top \\
    -s $SNAPSHOT \\
    -timescale 1ns/1ps \\
    -debug typical]

puts "--- Simulating ---"
run_cmd [list xsim $SNAPSHOT \\
    -testplusarg UVM_TESTNAME=${{DESIGN}}_smoke_test \\
    -runall \\
    -log xsim.log]

puts "Simulation complete. Log: xsim.log"
"""


def _gen_all_content(ir: IR, vplan_result) -> dict[str, str]:
    """Generate all UVM TB file contents as a dict of filename -> content.

    This is the internal generation engine used by both generate_uvm_tb()
    (writes to disk) and structure_gen.generate() (returns Artifacts).

    Args:
        ir: Populated IR for the design.
        vplan_result: VplanParseResult or None.

    Returns:
        Dict mapping flat filename to file content string.
    """
    d = ir.design_name

    # Build COV stub info from vplan_result.
    # vplan_result.cov_items is a dict[str, dict] keyed by COV ID.
    # Normalise to a list of simple objects so _cov_stub_names / _gen_cov_stub
    # can access .id, .name, etc. with attribute syntax.
    class _CovItem:  # lightweight adapter — no external dependency
        def __init__(self, cov_id: str, data: dict) -> None:
            self.id = cov_id
            self.name = data.get("name", "")
            self.linked_requirements = data.get("linked_requirements", [])
            self.stimulus_strategy = data.get("stimulus_strategy", "")
            self.boundary_values = data.get("boundary_values", "")
            self.seq_status = data.get("seq_status", "NONE") or "NONE"
            self.stimulus_vsl = data.get("stimulus_vsl", "") or ""
            self.vsl_steps = parse_vsl_stimulus(self.stimulus_vsl)
            self.vsl_notes = data.get("vsl_notes", "") or ""
            self.seq_review = data.get("seq_review", "DRAFT") or "DRAFT"

    raw_cov_items = {}
    if vplan_result is not None and hasattr(vplan_result, "cov_items"):
        raw_cov_items = vplan_result.cov_items or {}

    # Handle both dict[str, dict] (vplan_parser) and list (legacy)
    if isinstance(raw_cov_items, dict):
        cov_items = [_CovItem(k, v) for k, v in raw_cov_items.items()]
    else:
        cov_items = list(raw_cov_items)

    cov_stub_filenames: list[str] = []
    cov_stub_class_vars: list[tuple[str, str]] = []
    cov_stub_contents: dict[str, str] = {}

    for item in cov_items:
        vsl_steps = getattr(item, "vsl_steps", None) or []
        if vsl_steps:
            logger.debug("VSL parsed for %s: %d step(s)", item.id, len(vsl_steps))
        class_name, var_name, file_name = _cov_stub_names(item)
        cov_stub_filenames.append(file_name)
        cov_stub_class_vars.append((class_name, var_name))
        cov_stub_contents[file_name] = _gen_cov_stub(d, item)

    files: dict[str, str] = {
        f"{d}_if.sv":                   _gen_if(d, ir),
        f"{d}_pkg.sv":                  _gen_pkg(d, cov_stub_filenames),
        f"{d}_seq_item.sv":             _gen_seq_item(d),
        f"{d}_seqr.sv":                 _gen_seqr(d),
        f"{d}_base_seq.sv":             _gen_base_seq(d),
        f"{d}_driver.sv":               _gen_driver(d, ir),
        f"{d}_monitor.sv":              _gen_monitor(d, ir),
        f"{d}_agent.sv":                _gen_agent(d),
        f"{d}_scoreboard.sv":           _gen_scoreboard(d, vplan_result),
        f"{d}_coverage_subscriber.sv":  _gen_coverage_subscriber(d, vplan_result),
        f"{d}_env.sv":                  _gen_env(d),
        f"{d}_test.sv":                 _gen_test(d),
        f"{d}_smoke_seq.sv":            _gen_smoke_seq(d),
        f"{d}_regression_test.sv":      _gen_regression_test(d, cov_stub_class_vars),
        "tb_top.sv":                    _gen_tb_top(d, ir),
        "build.tcl":                    _gen_build_tcl(d, ir),
    }

    # Add COV stub files
    files.update(cov_stub_contents)

    return files


def generate_uvm_tb(ir: IR, vplan_result, out_dir: str) -> list[str]:
    """Generate all STD-003B UVM testbench files under out_dir/tb/.

    Creates the 15 required files (plus one per COV item if vplan_result
    is provided) under out_dir/tb/ and out_dir/tb/scripts/vivado/.

    Never-overwrite contract: if a file already exists at the target path
    it is skipped and a warning is logged. The file is NOT returned in the
    output list if skipped.

    Args:
        ir: Populated IR for the design.
        vplan_result: VplanParseResult or None; drives scoreboard shadow init,
            coverage bins, and COV stub file generation.
        out_dir: Root output directory. TB files go under out_dir/tb/.

    Returns:
        List of file paths that were written (skipped files not included).
    """
    tb_dir = os.path.join(out_dir, "tb")
    scripts_dir = os.path.join(tb_dir, "scripts", "vivado")
    os.makedirs(tb_dir, exist_ok=True)
    os.makedirs(scripts_dir, exist_ok=True)

    all_content = _gen_all_content(ir, vplan_result)
    written: list[str] = []

    for filename, content in all_content.items():
        if filename == "build.tcl":
            dest = os.path.join(scripts_dir, filename)
        else:
            dest = os.path.join(tb_dir, filename)

        if os.path.exists(dest):
            logger.warning(
                "generate_uvm_tb: skipping existing file %s (never-overwrite)", dest
            )
            continue

        with open(dest, "w", encoding="utf-8") as fh:
            fh.write(content)
        written.append(dest)

    return written
