# ===========================================================
# FILE:         agents/scaffold_gen.py
# PROJECT:      pssgen — AI-Driven PSS + UVM + C Testbench Generator
# COPYRIGHT:    Copyright (c) 2026 BelTech Systems LLC
# LICENSE:      MIT License — see LICENSE file for details
# ===========================================================
#
# DESCRIPTION:
#   Generates _generated.intent and _generated.req scaffold files from IR
#   and intent parse results. All machine-inferred lines are tagged with
#   [GENERATED] to distinguish them from human-authored content. Both output
#   files include a human-contribution notice and are never overwritten.
#
# LAYER:        3 — agents
# PHASE:        v3a
#
# FUNCTIONS:
#   generate_intent_scaffold(ir, intent_result, out_path)
#     Write a _generated.intent scaffold with [GENERATED] port entries and gaps section.
#   generate_req_scaffold(ir, intent_result, out_path)
#     Write a _generated.req scaffold with skeleton entries for each intent req ID.
#
# DEPENDENCIES:
#   Standard library:  os
#   Internal:          ir
#
# HISTORY:
#   v3a   2026-03-28  SB  Initial implementation; intent and req scaffold generation
#
# ===========================================================
"""agents/scaffold_gen.py — Intent and requirements scaffold file generator.

Phase: v3a
Layer: 3 (agent)

Generates _generated.intent and _generated.req scaffold files from the IR
and intent parse results. Output files include human-contribution notices
and [GENERATED] markers to distinguish machine-generated content from
human-authored content.

The never-overwrite contract: these files are written only when they do not
already exist at the target path. Callers are responsible for enforcing this.
"""
import os
from ir import IR

# Human contribution notice included verbatim in every scaffold file.
_HUMAN_NOTICE = """\
# NOTE: This file was generated by pssgen as a starting point.
# All [GENERATED] entries require human review.
# Entries without [GENERATED] prefix are human-authored.
# This file will never be overwritten by pssgen.
# Copyright in this file, after human review and editing,
# rests with the engineer who reviewed and edited it.
"""

# Roles that are candidates for intent gap detection
_GAP_ROLES = {"control", "data"}


def _infer_intent_gaps(ir: IR, intent_result) -> list[str]:
    """Identify ports whose roles are not covered by intent sections.

    A port is considered covered if its name appears in any section content
    of the intent result (case-insensitive substring match).

    Args:
        ir: Populated IR for the design.
        intent_result: IntentParseResult (or None) from intent parsing.

    Returns:
        List of port names that have no mention in intent sections.
    """
    if intent_result is None:
        # All control/data ports are gaps when no intent was provided
        return [p.name for p in ir.ports if p.role in _GAP_ROLES]

    # Flatten all intent content into a single lowercase string for search
    all_content = " ".join(
        " ".join(lines)
        for lines in intent_result.sections.values()
    ).lower()

    gaps = []
    for port in ir.ports:
        if port.role in _GAP_ROLES:
            if port.name.lower() not in all_content:
                gaps.append(port.name)
    return gaps


def generate_intent_scaffold(ir: IR, intent_result, out_path: str) -> str:
    """Generate a _generated.intent scaffold file.

    Writes a structured intent scaffold with [GENERATED] markers for each
    port, includes existing intent sections if present, and appends an
    intent_gaps section for uncovered ports.

    Args:
        ir: Populated IR for the design.
        intent_result: IntentParseResult from intent parsing, or None if no
            intent file was provided.
        out_path: Full file path to write the scaffold to.

    Returns:
        The file path written (same as out_path).
    """
    gaps = _infer_intent_gaps(ir, intent_result)

    lines: list[str] = []
    lines.append(_HUMAN_NOTICE)
    lines.append(f"# verification intent scaffold: {ir.design_name}")
    lines.append(f"# generated from: {ir.hdl_source}")
    lines.append("")

    # Include existing sections from intent_result (if any)
    if intent_result is not None and intent_result.sections:
        for heading, content_lines in intent_result.sections.items():
            lines.append(f"{heading}:")
            for content_line in content_lines:
                lines.append(f"  {content_line.strip()}")
            lines.append("")

    # Add [GENERATED] port sections
    lines.append("port behaviors:")
    for port in ir.ports:
        role_desc = _role_description(port.role, port.direction, port.width)
        lines.append(
            f"  [GENERATED] {port.name} ({port.direction} {port.width}-bit,"
            f" role={port.role}): {role_desc}"
        )
    lines.append("")

    # Intent gaps section
    if gaps:
        lines.append("intent gaps:")
        for gap_port in gaps:
            lines.append(
                f"  [GENERATED] {gap_port}: no verification intent found —"
                f" human review required"
            )
        lines.append("")

    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    return out_path


def generate_req_scaffold(ir: IR, intent_result, out_path: str) -> str:
    """Generate a _generated.req scaffold file.

    Writes skeleton requirement entries for each ID found in the intent
    result. If no IDs are present, writes a placeholder entry.

    Args:
        ir: Populated IR for the design.
        intent_result: IntentParseResult from intent parsing, or None.
        out_path: Full file path to write the scaffold to.

    Returns:
        The file path written (same as out_path).
    """
    req_ids: list[str] = []
    if intent_result is not None and intent_result.req_ids:
        req_ids = intent_result.req_ids

    lines: list[str] = []
    lines.append(_HUMAN_NOTICE)
    lines.append(f"# requirements scaffold: {ir.design_name}")
    lines.append(f"# generated from: {ir.hdl_source}")
    lines.append("")

    if req_ids:
        for rid in req_ids:
            lines.append(f"[{rid}] [GENERATED] Requirement statement — human review required.")
            lines.append("  verification: simulation")
            lines.append("")
    else:
        lines.append(
            f"[{ir.design_name.upper()}-REQ-001] [GENERATED] "
            "Placeholder requirement — replace with project-specific requirement."
        )
        lines.append("  verification: simulation")
        lines.append("")

    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    return out_path


def _role_description(role: str, direction: str, width: int) -> str:
    """Return a human-readable description hint for a port role.

    Args:
        role: Port role string (clock, reset_n, reset, control, data).
        direction: Port direction (input, output, inout).
        width: Port bit width.

    Returns:
        A short description hint string.
    """
    descriptions = {
        "clock": "synchronous clock — verify all synchronous behavior",
        "reset_n": "active-low reset — verify reset assertion and deassertion",
        "reset": "active-high reset — verify reset assertion and deassertion",
        "control": f"{width}-bit control signal — describe expected behavior",
        "data": f"{width}-bit data {direction} — describe expected values and ranges",
    }
    return descriptions.get(role, f"{width}-bit {direction} — describe expected behavior")
