"""
Generates docs/pssgen_regmap_template.xlsx
Run from the project root with the venv active:
    python docs/make_regmap_template.py
"""
import os
from openpyxl import Workbook
from openpyxl.styles import (
    Font, PatternFill, Alignment, Border, Side
)
from openpyxl.comments import Comment
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.datavalidation import DataValidation

# ── Palette ──────────────────────────────────────────────────────────────────
DARK_BLUE   = "1F3864"
LIGHT_BLUE  = "D6E4F0"
LIGHT_YELLOW = "FFFACD"
WHITE       = "FFFFFF"
REQUIRED_HEADER_FILL = PatternFill("solid", fgColor=LIGHT_YELLOW)
STANDARD_HEADER_FILL = PatternFill("solid", fgColor=DARK_BLUE)
EXAMPLE_FILL         = PatternFill("solid", fgColor=LIGHT_BLUE)

def hdr_font(required=False):
    color = "000000" if required else WHITE
    return Font(name="Arial", bold=True, color=color, size=10)

def body_font(italic=False):
    return Font(name="Arial", italic=italic, size=10)

def make_header_cell(ws, row, col, value, required=False, comment_text=None):
    cell = ws.cell(row=row, column=col, value=value)
    cell.fill = REQUIRED_HEADER_FILL if required else STANDARD_HEADER_FILL
    cell.font  = hdr_font(required=required)
    cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    if comment_text:
        c = Comment(comment_text, "pssgen")
        c.width  = 300
        c.height = 120
        cell.comment = c
    return cell

def set_example_row(ws, row_num, values):
    for col, val in enumerate(values, start=1):
        cell = ws.cell(row=row_num, column=col, value=val)
        cell.fill = EXAMPLE_FILL
        cell.font = body_font(italic=True)
        cell.alignment = Alignment(vertical="center", wrap_text=True)

def auto_width(ws, min_width=12):
    for col in ws.columns:
        max_len = min_width
        col_letter = get_column_letter(col[0].column)
        for cell in col:
            if cell.value:
                max_len = max(max_len, min(len(str(cell.value)), 40))
        ws.column_dimensions[col_letter].width = max_len + 2

# ── SHEET: Globals ────────────────────────────────────────────────────────────
def build_globals(wb):
    ws = wb.active
    ws.title = "Globals"

    # Cover note in A1
    ws["A1"] = (
        "pssgen Register Map Template v1.0\n"
        "Generated by pssgen — BelTech Systems LLC\n"
        "Fill in the Value column on this sheet, then\n"
        "populate the Blocks, RegisterMap, and Enums sheets.\n"
        "Delete the [EXAMPLE] rows before use."
    )
    ws["A1"].font = Font(name="Arial", bold=True, size=10)
    ws["A1"].alignment = Alignment(wrap_text=True, vertical="top")
    ws.row_dimensions[1].height = 72
    ws.merge_cells("A1:C1")

    # Header row at row 2
    headers = [
        ("Key",         "Configuration key name. Do not edit."),
        ("Value",       "Your project-specific value. Edit this column only."),
        ("Description", "Explains what this key controls. Do not edit."),
    ]
    for col, (hdr, cmt) in enumerate(headers, start=1):
        make_header_cell(ws, 2, col, hdr, required=False, comment_text=cmt)

    ws.freeze_panes = "A3"

    # Data rows
    rows = [
        ("project_name",    "MY_PROJECT",   "Project or IP block name"),
        ("revision",        "0.1",          "Semantic version of this register spec"),
        ("author",          "",             "Owner/author of this register map"),
        ("date",            "",             "Date of this revision (YYYY-MM-DD)"),
        ("data_width_bits", "32",           "Bus data width: 8, 16, 32, or 64"),
        ("endianness",      "Little",       "Little or Big"),
        ("bus_type",        "AXI4-Lite",    "AXI4-Lite, APB, Wishbone, or custom"),
        ("base_address",    "0x0000_0000",  "Base address of this IP block (hex)"),
        ("address_stride",  "0x04",         "Default register stride in bytes (hex)"),
    ]
    for r_idx, (key, val, desc) in enumerate(rows, start=3):
        ws.cell(row=r_idx, column=1, value=key).font  = body_font()
        ws.cell(row=r_idx, column=2, value=val).font  = body_font()
        ws.cell(row=r_idx, column=3, value=desc).font = body_font()

    auto_width(ws)
    ws.column_dimensions["B"].width = 20
    ws.column_dimensions["C"].width = 40

# ── SHEET: Blocks ─────────────────────────────────────────────────────────────
def build_blocks(wb):
    ws = wb.create_sheet("Blocks")

    block_headers = [
        ("block_name",
         "Name of the register block. Must be a valid HDL identifier.\n"
         "Matches block_name in the RegisterMap sheet."),
        ("base_address",
         "Block base address in hex. e.g. 0x4000_0000"),
        ("data_width_bits",
         "Bus data width for this block: 8, 16, 32, or 64"),
        ("reset_domain",
         "Name of the reset domain signal. e.g. RST_N, periph_rst"),
        ("clock_domain",
         "Name of the clock domain signal. e.g. CLK, periph_clk"),
        ("description",
         "Plain English description of what this block does."),
    ]
    for col, (hdr, cmt) in enumerate(block_headers, start=1):
        make_header_cell(ws, 1, col, hdr, comment_text=cmt)

    ws.freeze_panes = "A2"

    example = ["MY_BLOCK", "0x0000_0000", "32", "PERIPH_RST", "periph_clk",
               "My peripheral block"]
    example[0] = "[EXAMPLE — delete this row]  " + example[0]
    set_example_row(ws, 2, example)

    auto_width(ws)

# ── SHEET: RegisterMap ────────────────────────────────────────────────────────
# Column definitions: (header, required, comment)
REGMAP_COLS = [
    ("block_name",
     True,
     "Must match a block_name in the Blocks sheet.\n"
     "Repeat for every field row in this block."),
    ("reg_name",
     True,
     "Register name — HDL identifier. e.g. CTRL, STATUS, BAUD_DIV.\n"
     "Repeat for every field row in this register."),
    ("reg_description",
     True,
     "Plain English description of the register.\n"
     "Repeat for every field row in this register."),
    ("address_offset",
     True,
     "Hex offset from block base address. e.g. 0x00, 0x04, 0x08.\n"
     "Repeat for every field row in this register."),
    ("reg_width_bits",
     True,
     "Total register width: 8, 16, 32, or 64.\n"
     "Repeat for every field row in this register."),
    ("field_name",
     True,
     "Field name — HDL identifier. e.g. ENABLE, TX_READY, BAUD_DIV.\n"
     "Must be unique within the register."),
    ("bit_offset",
     True,
     "LSB position of this field (0-based).\n"
     "e.g. 0 for a field starting at bit 0."),
    ("bit_width",
     True,
     "Number of bits in this field.\n"
     "bit_offset + bit_width - 1 = MSB position."),
    ("access",
     True,
     "Combined SW/HW access type.\n"
     "Valid: RW, RO, WO, W1C, W1S, RC, RS, NA"),
    ("reset_value",
     True,
     "Reset value in hex. e.g. 0x0, 0xFF.\n"
     "Must fit within bit_width."),
    ("volatile",
     True,
     "YES if hardware can change this field without a software write.\n"
     "NO otherwise. Valid: YES, NO"),
    ("hw_access",
     True,
     "How hardware uses this field.\n"
     "Valid: NA, RC, W1C, set-on-1, set-on-read, write-only,\n"
     "set-by-input, status/clear, write-1-to-clear, pulse, TOG"),
    ("sw_access",
     True,
     "Software access type independent of HW.\n"
     "Valid: RW, RO, WO, RC, RS, NA"),
    ("field_kind",
     True,
     "Semantic type of this field.\n"
     "Valid: normal, status, reserved, const, alias"),
    ("enum_ref",
     True,
     "Name of an enum defined in the Enums sheet.\n"
     "Leave blank if field uses raw numeric values. e.g. spi_mode_t"),
    ("uvm_has_coverage",
     True,
     "YES to generate a UVM covergroup for this field.\n"
     "NO to skip coverage generation. Valid: YES, NO"),
    ("req_id",
     False,
     "Optional requirement ID from the .req file.\n"
     "Enables traceability in the pssgen gap report.\n"
     "e.g. FUNC-REQ-201, SYS-REQ-047\n"
     "Leave blank if no formal requirement traces here."),
    ("pss_action",
     False,
     "Optional PSS action name for this field's verification sequence.\n"
     "If blank, pssgen derives a name from register and field names.\n"
     "e.g. uart_ctrl_enable, spi_mode_set"),
    ("hdl_path",
     False,
     "Optional hierarchical path to this field in RTL.\n"
     "Used for UVM backdoor access.\n"
     "e.g. dut.uart0.ctrl_reg.enable_bit\n"
     "Leave blank if backdoor access not needed."),
    ("description",
     False,
     "Plain English description of this field.\n"
     "What it does, not what it is."),
]

def build_registermap(wb):
    ws = wb.create_sheet("RegisterMap")

    for col, (hdr, required, cmt) in enumerate(REGMAP_COLS, start=1):
        make_header_cell(ws, 1, col, hdr, required=required, comment_text=cmt)

    ws.freeze_panes = "A2"

    # Example row 1 — RW control field
    ex1 = [
        "MY_BLOCK", "CTRL", "Control Register", "0x00", "32",
        "ENABLE", "0", "1", "RW", "0x0", "NO", "NA", "RW",
        "normal", "", "YES", "FUNC-REQ-201", "ctrl_enable",
        "dut.my_block.ctrl.enable", "Enable the peripheral core",
    ]
    ex1[0] = "[EXAMPLE — delete this row]  " + ex1[0]
    set_example_row(ws, 2, ex1)

    # Example row 2 — RO status field
    ex2 = [
        "MY_BLOCK", "STATUS", "Status Register", "0x04", "32",
        "TX_READY", "0", "1", "RO", "0x0", "YES", "set-on-1", "RO",
        "status", "", "YES", "FUNC-REQ-202", "",
        "", "Transmit ready — set by hardware when TX buffer empty",
    ]
    ex2[0] = "[EXAMPLE — delete this row]  " + ex2[0]
    set_example_row(ws, 3, ex2)

    # ── Data validation (via hidden ListsHelper sheet) ────────────────────────
    # Map column index (1-based) to validation list name
    VALIDATIONS = {
        9:  "access_list",
        11: "volatile_list",
        12: "hw_access_list",
        13: "sw_access_list",
        14: "field_kind_list",
        16: "uvm_cov_list",
    }
    for col_idx, list_name in VALIDATIONS.items():
        col_letter = get_column_letter(col_idx)
        dv = DataValidation(
            type="list",
            formula1=f"ListsHelper!${col_letter}$2:${col_letter}$20",
            allow_blank=True,
            showErrorMessage=True,
            errorTitle="Invalid value",
            error="Select a value from the dropdown list.",
        )
        dv.sqref = f"{col_letter}2:{col_letter}1048576"
        ws.add_data_validation(dv)

    auto_width(ws)

# ── SHEET: Enums ──────────────────────────────────────────────────────────────
def build_enums(wb):
    ws = wb.create_sheet("Enums")

    enum_headers = [
        ("enum_name",
         "Enum type name. Referenced by enum_ref in RegisterMap.\n"
         "e.g. spi_mode_t\n"
         "Repeat this name on every row that belongs to the same enum."),
        ("value",
         "Integer value for this enum symbol. e.g. 0, 1, 2, 3"),
        ("symbol",
         "Symbolic name. e.g. MODE0, DISABLED, ENABLED"),
        ("description",
         "What this value means in the context of the field.\n"
         "e.g. CPOL=0, CPHA=0"),
    ]
    for col, (hdr, cmt) in enumerate(enum_headers, start=1):
        make_header_cell(ws, 1, col, hdr, comment_text=cmt)

    ws.freeze_panes = "A2"

    examples = [
        ("example_mode_t", "0", "DISABLED", "Feature disabled"),
        ("example_mode_t", "1", "ENABLED",  "Feature enabled"),
        ("example_mode_t", "2", "BYPASS",   "Bypass mode active"),
    ]
    for r_idx, row in enumerate(examples, start=2):
        vals = list(row)
        if r_idx == 2:
            vals[0] = "[EXAMPLE — delete this row]  " + vals[0]
        set_example_row(ws, r_idx, vals)

    auto_width(ws)

# ── SHEET: ListsHelper (hidden) ───────────────────────────────────────────────
# Each validation list goes in its own column, header in row 1, values from row 2.
# Column positions must match the col_idx → list_name mapping in build_registermap.
# Col 9 = I, 11 = K, 12 = L, 13 = M, 14 = N, 16 = P

LISTS = {
    9:  ("access",          ["RW", "RO", "WO", "W1C", "W1S", "RC", "RS", "NA"]),
    11: ("volatile",        ["YES", "NO"]),
    12: ("hw_access",       ["NA", "RC", "W1C", "set-on-1", "set-on-read",
                             "write-only", "set-by-input", "status/clear",
                             "write-1-to-clear", "pulse", "TOG"]),
    13: ("sw_access",       ["RW", "RO", "WO", "RC", "RS", "NA"]),
    14: ("field_kind",      ["normal", "status", "reserved", "const", "alias"]),
    16: ("uvm_has_coverage",["YES", "NO"]),
}

def build_lists_helper(wb):
    ws = wb.create_sheet("ListsHelper")

    for col_idx, (label, values) in LISTS.items():
        col_letter = get_column_letter(col_idx)
        ws[f"{col_letter}1"] = label
        ws[f"{col_letter}1"].font = Font(name="Arial", bold=True, size=9)
        for r, v in enumerate(values, start=2):
            ws[f"{col_letter}{r}"] = v
            ws[f"{col_letter}{r}"].font = Font(name="Arial", size=9)

    ws.sheet_state = "hidden"

# ── Assemble ──────────────────────────────────────────────────────────────────
def main():
    wb = Workbook()

    build_globals(wb)
    build_blocks(wb)
    build_registermap(wb)
    build_enums(wb)
    build_lists_helper(wb)

    out_path = os.path.join(
        os.path.dirname(__file__), "pssgen_regmap_template.xlsx"
    )
    wb.save(out_path)
    print(f"Saved: {out_path}")

if __name__ == "__main__":
    main()
